-- TAO BANG TAI KHOAN
CREATE TABLE TAIKHOAN (
  MATK NUMBER NOT NULL, 
  MANHOM NUMBER NOT NULL, 
  USERNAME VARCHAR2(100) NOT NULL, 
  PASSWORD VARCHAR2(100),
  TRANGTHAI NUMBER,
  CONSTRAINT PK_TK PRIMARY KEY (MATK)
);

-- TAO BANG BENH NHAN
CREATE TABLE BENHNHAN (
  MABN NUMBER NOT NULL, 
  MATK NUMBER, 
  CCCD VARCHAR2(12) NOT NULL, 
  HOTEN VARCHAR2(255) NOT NULL, 
  NGAYSINH DATE,
  GIOITINH VARCHAR2(5), 
  SDT VARCHAR2(30), 
  DIACHI VARCHAR2(255),
  TIENSUBENH VARCHAR2(255),
  DIUNG VARCHAR(255),
  EMAIL VARCHAR2(255),
  CONSTRAINT PK_BN PRIMARY KEY (MABN)
);

-- TAO BANG BAC SI
CREATE TABLE BACSI (
  MABS NUMBER NOT NULL,
  MATK NUMBER NOT NULL,
  CCCD VARCHAR2(12) NOT NULL, 
  HOTEN VARCHAR2(255) NOT NULL, 
  TRINHDO VARCHAR2(100),
  GIOITINH VARCHAR2(5),
  SDT VARCHAR2(30), 
  NGAYSINH DATE,
  DIACHI VARCHAR2(255),
  CHUYENKHOA VARCHAR2(255),
  CONSTRAINT PK_BS PRIMARY KEY (MABS)
);

-- TAO BANG PHAN CONG KHAM
CREATE TABLE PHANCONGKHAM (
  MABS NUMBER,
  THU VARCHAR2(100),
  GIOBATDAU VARCHAR2(100),
  GIOKETTHUC VARCHAR2(100),
  CONSTRAINT PK_PCK PRIMARY KEY (MABS, THU)
);

-- TAO BANG LE TAN
CREATE TABLE LETAN (
  MALT NUMBER NOT NULL,
  MATK NUMBER NOT NULL,
  CCCD VARCHAR2(12) NOT NULL,
  HOTEN VARCHAR2(255) NOT NULL, 
  SDT VARCHAR2(30), 
  NGAYSINH DATE,
  DIACHI VARCHAR2(255),
  GIOITINH VARCHAR2(5),
  CONSTRAINT PK_LT PRIMARY KEY (MALT)
);

-- TAO BANG PHONG KHAM
CREATE TABLE PHONGKHAM (
  MAPHONG NUMBER NOT NULL,
  TENPHONG VARCHAR2(100),
  SOPHONG NUMBER,
  TANG NUMBER,
  CONSTRAINT PK_PHONG PRIMARY KEY (MAPHONG)
);

-- TAO BANG BENH
CREATE TABLE BENH (
  MABENH NUMBER NOT NULL , 
  MAICD VARCHAR2(10) , 
  TENBENH VARCHAR2(500),
  TRANGTHAI NUMBER,
  CONSTRAINT PK_BENH PRIMARY KEY (MABENH)
);

-- TAO BANG LOAI HOA DON
CREATE TABLE LOAIHD (
  MALOAIHD NUMBER NOT NULL,
  TENLOAIHD VARCHAR2(100),
  CONSTRAINT PK_LOAIHD PRIMARY KEY (MALOAIHD)
);

-- TAO BANG LOAI DICH VU
CREATE TABLE LOAIDV (
  MALOAIDV NUMBER NOT NULL,
  TENLOAIDV VARCHAR2(100),
  TRANGTHAI NUMBER,
  CONSTRAINT PK_LOAIDV PRIMARY KEY (MALOAIDV)
);

-- TAO BANG DICH VU
CREATE TABLE DICHVU (
  MADV NUMBER NOT NULL,
  MALOAIDV NUMBER NOT NULL,
  TENDV VARCHAR2(100),
  GIADV NUMBER,
  TRANGTHAI NUMBER,
  CONSTRAINT PK_DV PRIMARY KEY (MADV)
);

-- TAO BANG PHIEU KHAM
CREATE TABLE PHIEUKHAM (
  MAPK NUMBER NOT NULL,
  MABN NUMBER NOT NULL,
  MABSC NUMBER NOT NULL,
  MADVK NUMBER NOT NULL,
  MAHD NUMBER NOT NULL,
  MAPHONG NUMBER NOT NULL,
  NGAYKHAM DATE,
  NGAYDATLICH DATE, 
  GIODATLICH VARCHAR2(100),
  TRANGTHAITH VARCHAR2(100),
  STT NUMBER, 
  HUYETAP NUMBER,
  LYDOKHAM VARCHAR2(255), 
  CHIEUCAO NUMBER, 
  CANNANG NUMBER,
  TRIEUCHUNGBENH VARCHAR2(255),
  TINHTRANGCOTHE VARCHAR2(255), 
  KETLUAN VARCHAR2(255),
  GIADVLUCDK NUMBER,
  CONSTRAINT PK_PK PRIMARY KEY (MAPK)  
);

-- TAO BANG KET QUA CAN LAM SAN
CREATE TABLE KETQUADICHVUCLS (
  MAKQ NUMBER NOT NULL,
  MAPK NUMBER NOT NULL,
  MABSTH NUMBER NOT NULL, 
  MADVCLS NUMBER NOT NULL,
  MAPHONG NUMBER NOT NULL,
  MAHD NUMBER NOT NULL,
  TRANGTHAITH VARCHAR2(100),
  STT NUMBER,
  KETLUANCLS VARCHAR2(255),
  IMAGE VARCHAR2(255),
  MOTA VARCHAR2(500),
  GIADVCLSLUCDK NUMBER,
  THOIGIANTAO DATE,
  CONSTRAINT PK_KQDV PRIMARY KEY (MAKQ)  
);

-- TAO BANG CHI TIET BENH
CREATE TABLE CHITIETBENH (
  MAPK NUMBER NOT NULL,
  MABENH NUMBER NOT NULL,
  CONSTRAINT PK_CTB PRIMARY KEY (MAPK, MABENH)
);

-- TAO BANG HOA DON
CREATE TABLE HOADON (
  MAHD NUMBER NOT NULL,
  MALT NUMBER NOT NULL,
  MALOAIHD NUMBER NOT NULL,
  TDTT DATE,
  TTTT VARCHAR2(100),
  THANHTIEN NUMBER,
  PTTT VARCHAR2(100),
  CONSTRAINT PK_HD PRIMARY KEY (MAHD)  
);

-- TAO BANG THUOC
CREATE TABLE THUOC (
  MATHUOC NUMBER NOT NULL,
  MADVT NUMBER NOT NULL,
  TENTHUOC VARCHAR2(100),
  THANHPHAN VARCHAR2(100),
  TRANGTHAI NUMBER,
  CONSTRAINT PK_MATHUOC PRIMARY KEY (MATHUOC)  
);

-- TAO BANG DON VI THUOC
CREATE TABLE DONVITHUOC (
  MADVT NUMBER NOT NULL,
  TENDONVI VARCHAR2(20),
  TRANGTHAI NUMBER,
  CONSTRAINT PK_DVT PRIMARY KEY (MADVT)
);

-- TAO BANG LO THUOC
CREATE TABLE LOTHUOC (
  MALOTHUOC NUMBER NOT NULL,
  MATHUOC NUMBER NOT NULL,
  NHACC VARCHAR2(100),
  SOLUONGTON NUMBER,
  SOLUONGNHAP NUMBER,
  HANSD DATE,
  GIANHAP NUMBER,
  NGAYNHAP DATE,
  GIABAN NUMBER,
  TRANGTHAI NUMBER,
  CONSTRAINT PK_LOTHUOC PRIMARY KEY (MALOTHUOC)  
);

-- TAO BANG DON THUOC
CREATE TABLE DONTHUOC (
  MADT NUMBER NOT NULL,
  MAHD NUMBER NOT NULL, 
  MAPK NUMBER NOT NULL,
  GIADT NUMBER,
  NGAYLAP DATE,
  CONSTRAINT PK_DT PRIMARY KEY (MADT)  
);

-- TAO BANG CHI TIET DON THUOC
CREATE TABLE CTDT (
  MACTDT NUMBER NOT NULL,
  MADT NUMBER NOT NULL,
  MATHUOC NUMBER NOT NULL,
  SOLANUONG NUMBER,
  SOLUONGUONG NUMBER,
  TRANGTHAIDATLICH VARCHAR2(100),
  SOLUONGTHUOC NUMBER,
  GIABANLUCKE NUMBER,
  GHICHU VARCHAR2(255),
  CONSTRAINT PK_CTDT PRIMARY KEY (MACTDT)
);

-- TAO BANG GIO DAT LICH
CREATE TABLE GIODATLICH (
  MAGIO NUMBER NOT NULL,
  MACTDT NUMBER NOT NULL,
  THOIGIAN VARCHAR2(100),
  CONSTRAINT PK_GIO PRIMARY KEY (MAGIO)
);

-- TAO BANG NHOM NGUOI DUNG
CREATE TABLE NHOM (
  MANHOM NUMBER NOT NULL,
  TENNHOM VARCHAR2(255),
  TRANGTHAI NUMBER,
  CONSTRAINT PK_NHOM PRIMARY KEY (MANHOM)
);

-- TAO BANG VAI TRO (QUYEN)
CREATE TABLE VAITRO (
  MAVAITRO NUMBER NOT NULL, 
  URL VARCHAR2(300),
  MOTA VARCHAR2(100),
  CONSTRAINT PK_VT PRIMARY KEY (MAVAITRO)
);

-- TAO BANG NHOM_VAI TRO
CREATE TABLE NHOM_VAITRO (
  MANHOM NUMBER NOT NULL,
  MAVAITRO NUMBER NOT NULL,
  CONSTRAINT PK_NHOM_VAITRO PRIMARY KEY (MANHOM, MAVAITRO)
);

-- TAO BANG THAM SO
CREATE TABLE THAMSO (
  MATHAMSO NUMBER,
  TENTHAMSO VARCHAR2(255),
  GIATRI NUMBER,
  CONSTRAINT PK_THAMSO PRIMARY KEY (MATHAMSO)
);

-- XEM BANG
SELECT * FROM NHOM;
SELECT * FROM NHOM_VAITRO;
SELECT * FROM THAMSO;
SELECT * FROM TAIKHOAN;
SELECT * FROM VAITRO;
SELECT * FROM BENHNHAN;
SELECT * FROM BACSI;
SELECT * FROM LETAN;
SELECT * FROM PHONGKHAM;
SELECT * FROM BENH;
SELECT * FROM LOAIHD;
SELECT * FROM DICHVU;
SELECT * FROM LOAIDV;
SELECT * FROM PHIEUKHAM;
SELECT * FROM KETQUADICHVUCLS;
SELECT * FROM CHITIETBENH;
SELECT * FROM DONTHUOC;
SELECT * FROM CTDT;
SELECT * FROM GIODATLICH;
SELECT * FROM THUOC;
SELECT * FROM DONVITHUOC;
SELECT * FROM LOTHUOC;
SELECT * FROM HOADON;

-- XOA BANG
DROP TABLE NHOM;
DROP TABLE VAITRO;
DROP TABLE NHOM_VAITRO;
DROP TABLE THAMSO;
DROP TABLE TAIKHOAN;
DROP TABLE VAITRO;
DROP TABLE BENHNHAN;
DROP TABLE BACSI;
DROP TABLE LETAN;
DROP TABLE PHONGKHAM;
DROP TABLE BENH;
DROP TABLE LOAIHD;
DROP TABLE DICHVU;
DROP TABLE LOAIDV;
DROP TABLE PHIEUKHAM;
DROP TABLE KETQUADICHVUCLS;
DROP TABLE CHITIETBENH;
DROP TABLE DONTHUOC;
DROP TABLE CTDT;
DROP TABLE GIODATLICH;
DROP TABLE THUOC;
DROP TABLE DONVITHUOC;
DROP TABLE LOTHUOC;
DROP TABLE HOADON;

DELETE FROM NHOM;
DELETE FROM NHOM_VAITRO;
DELETE FROM THAMSO;
DELETE FROM TAIKHOAN;
DELETE FROM VAITRO;
DELETE FROM BENHNHAN;
DELETE FROM BACSI;
DELETE FROM LETAN;
DELETE FROM PHONGKHAM;
DELETE FROM BENH;
DELETE FROM LOAIHD;
DELETE FROM DICHVU;
DELETE FROM LOAIDV;
DELETE FROM PHIEUKHAM;
DELETE FROM KETQUADICHVUCLS;
DELETE FROM CHITIETBENH;
DELETE FROM DONTHUOC;
DELETE FROM CTDT;
DELETE FROM GIODATLICH;
DELETE FROM THUOC;
DELETE FROM DONVITHUOC;
DELETE FROM LOTHUOC;
DELETE FROM HOADON;