/*========================= PROCEDURE INSERT, UPDATE, DELETE ========================*/
/*========================= BANG THAM SO ========================*/

-- CAP NHAT THAM SO
CREATE OR REPLACE PROCEDURE UPDATE_THAMSO (
  PAR_TENTHAMSO THAMSO.TENTHAMSO%TYPE,
  PAR_GIATRI THAMSO.GIATRI%TYPE)
AS
BEGIN
  UPDATE THAMSO
  SET GIATRI = PAR_GIATRI
  WHERE TENTHAMSO = PAR_TENTHAMSO;
  COMMIT;
END;
/

/*========================= BANG VAI TRO ========================*/

-- THEM VAI TRO
CREATE OR REPLACE PROCEDURE INSERT_VAITRO (
  PAR_URL VAITRO.URL%TYPE, 
  PAR_MOTA VAITRO.MOTA%TYPE, MAVT_OUT OUT NUMBER)
AS
BEGIN
  INSERT INTO VAITRO (MAVAITRO, URL, MOTA)
  VALUES (SEQ10_MAVT.NEXTVAL, PAR_URL, PAR_MOTA)
  RETURNING MAVAITRO INTO MAVT_OUT;
  
  COMMIT;
END;

-- CAP NHAT VAI TRO
CREATE OR REPLACE PROCEDURE UPDATE_VAITRO (
  PAR_MAVAITRO VAITRO.MAVAITRO%TYPE,
  PAR_URL VAITRO.URL%TYPE, 
  PAR_MOTA VAITRO.MOTA%TYPE)
AS
BEGIN
  UPDATE VAITRO
  SET URL = PAR_URL, MOTA = PAR_MOTA
  WHERE MAVAITRO = PAR_MAVAITRO;
  COMMIT;
END;

-- XOA VAI TRO
CREATE OR REPLACE PROCEDURE DELETE_VAITRO (
    P_MAVAITRO VAITRO.MAVAITRO%TYPE) 
AS
BEGIN
    DELETE FROM NHOM_VAITRO
    WHERE MAVAITRO = P_MAVAITRO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

/*========================= BANG NHOM_VAITRO ========================*/

-- THEM VAITRO VA GAN TRUC TIEP CHO ADMIN
CREATE OR REPLACE PROCEDURE INSERT_VAITRO_NHOM_VAITRO (
  PAR_URL VAITRO.URL%TYPE,
  PAR_MOTA VAITRO.MOTA%TYPE)
AS
    VAR_MAVT VAITRO.MAVAITRO%TYPE;
BEGIN

    INSERT_VAITRO(PAR_URL, PAR_MOTA, MAVT_OUT => VAR_MAVT);

    INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO)
    VALUES (1, VAR_MAVT);
END;

-- THEM NHOM_VAITRO
CREATE OR REPLACE PROCEDURE INSERT_NHOM_VAITRO (
  PAR_MANHOM NHOM_VAITRO.MANHOM%TYPE,
  PAR_MAVAITRO NHOM_VAITRO.MAVAITRO%TYPE)
AS
BEGIN

    INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO)
    VALUES (PAR_MANHOM, PAR_MAVAITRO);
END;


/*========================= BANG TAI KHOAN ========================*/

-- THEM TAI KHOAN
CREATE OR REPLACE PROCEDURE INSERT_TAIKHOAN (
  PAR_MANHOM TAIKHOAN.MANHOM%TYPE, 
  PAR_USERNAME TAIKHOAN.USERNAME%TYPE, 
  PAR_PASSWORD TAIKHOAN.PASSWORD%TYPE,
  MATK_OUT OUT TAIKHOAN.MATK%TYPE)
AS
BEGIN
  INSERT INTO TAIKHOAN (MATK, MANHOM, USERNAME, PASSWORD, TRANGTHAI)
  VALUES (SEQ3_MATK.NEXTVAL, PAR_MANHOM, PAR_USERNAME, PAR_PASSWORD, 1)
  RETURNING MATK INTO MATK_OUT;
  COMMIT;
END;

-- CAP NHAT TAI KHOAN
CREATE OR REPLACE PROCEDURE UPDATE_TAIKHOAN (
  PAR_MATK TAIKHOAN.MATK%TYPE,
  PAR_USERNAME TAIKHOAN.USERNAME%TYPE, 
  PAR_PASSWORD TAIKHOAN.PASSWORD%TYPE)
AS
BEGIN
  UPDATE TAIKHOAN
  SET USERNAME = PAR_USERNAME, PASSWORD = PAR_PASSWORD
  WHERE MATK = PAR_MATK;
  COMMIT;
END;

-- XOA TAI KHOAN
CREATE OR REPLACE PROCEDURE DELETE_TAIKHOAN (PAR_MATK TAIKHOAN.MATK%TYPE)
AS
BEGIN
  UPDATE TAIKHOAN
  SET TRANGTHAI = 0
  WHERE MATK = PAR_MATK;
  COMMIT;
END;

-- INSERT TAIKHOAN_BENHNHAN
-- THEM TAI KHOAN VA BENH NHAN
CREATE OR REPLACE PROCEDURE INSERT_TAIKHOAN_BENHNHAN (
  PAR_USERNAME TAIKHOAN.USERNAME%TYPE, PAR_PASSWORD TAIKHOAN.PASSWORD%TYPE, PAR_CCCD BENHNHAN.CCCD%TYPE, PAR_HOTEN BENHNHAN.HOTEN%TYPE, PAR_NGAYSINH BENHNHAN.NGAYSINH%TYPE, PAR_GIOITINH BENHNHAN.GIOITINH%TYPE,
  PAR_SDT BENHNHAN.SDT%TYPE, PAR_DIACHI BENHNHAN.DIACHI%TYPE, PAR_TIENSUBENH BENHNHAN.TIENSUBENH%TYPE, PAR_DIUNG BENHNHAN.DIUNG%TYPE, PAR_EMAIL BENHNHAN.EMAIL%TYPE, MABN_OUT OUT BENHNHAN.MABN%TYPE)
AS
  V_MATKOld TAIKHOAN.MATK%TYPE;
BEGIN
  INSERT_TAIKHOAN (4, PAR_USERNAME, PAR_PASSWORD, MATK_OUT => V_MATKOld);

  INSERT INTO BENHNHAN (MABN, MATK, CCCD, HOTEN, NGAYSINH, GIOITINH, SDT, DIACHI, TIENSUBENH, DIUNG, EMAIL)
  VALUES (SEQ2_MABN.NEXTVAL, V_MATKOld, PAR_CCCD, PAR_HOTEN, PAR_NGAYSINH, PAR_GIOITINH, PAR_SDT, PAR_DIACHI, PAR_TIENSUBENH, PAR_DIUNG, PAR_EMAIL)
  RETURNING MABN INTO MABN_OUT;
  COMMIT;

END;

-- THEM TAI KHOAN, UPDATE BENH NHAN
CREATE OR REPLACE PROCEDURE INSERT_TAIKHOAN_UPDATE_BENHNHAN (
  PAR_USERNAME TAIKHOAN.USERNAME%TYPE, PAR_PASSWORD TAIKHOAN.PASSWORD%TYPE, PAR_MABN BENHNHAN.MABN%TYPE, MABN_OUT OUT BENHNHAN.MABN%TYPE)
AS
  V_MATKOld TAIKHOAN.MATK%TYPE;
BEGIN
  INSERT_TAIKHOAN (4, PAR_USERNAME, PAR_PASSWORD, MATK_OUT => V_MATKOld);

  UPDATE BENHNHAN 
  SET MATK = V_MATKOld
  WHERE MABN = PAR_MABN
  RETURNING MABN INTO MABN_OUT;
  COMMIT;

END;


/*========================= BANG BAC SI ========================*/

-- THEM BAC SI
CREATE OR REPLACE PROCEDURE INSERT_BACSI (
  PAR_USERNAME TAIKHOAN.USERNAME%TYPE, PAR_PASSWORD TAIKHOAN.PASSWORD%TYPE,
  par_HoTen BACSI.HOTEN%TYPE, par_cccd BACSI.CCCD%TYPE, par_TrinhDo BACSI.TRINHDO%TYPE, 
  par_NgaySinh BACSI.NGAYSINH%TYPE, par_GioiTinh BACSI.GIOITINH%TYPE, par_sdt BACSI.SDT%TYPE, 
  par_DiaChi BACSI.DIACHI%TYPE, par_ChuyenKhoa BACSI.CHUYENKHOA%TYPE)

AS
  V_MATKOld TAIKHOAN.MATK%TYPE;
BEGIN
    INSERT_TAIKHOAN (2, PAR_USERNAME, PAR_PASSWORD, MATK_OUT => V_MATKOld);

    INSERT INTO BACSI (MABS, MATK, CCCD, HOTEN, TRINHDO, GIOITINH, SDT, NGAYSINH, DIACHI, CHUYENKHOA) 
    VALUES (SEQ1_MABS.NEXTVAL,V_MATKOld,par_cccd,par_HoTen,par_TrinhDo,par_GioiTinh,par_sdt,par_NgaySinh,par_DiaChi,par_ChuyenKhoa);

    COMMIT;
END;

-- CAP NHAT BAC SI
CREATE OR REPLACE PROCEDURE UPDATE_BACSI (
  par_Mabs BACSI.MABS%TYPE, par_HoTen BACSI.HOTEN%TYPE, par_cccd BACSI.CCCD%TYPE, par_TrinhDo BACSI.TRINHDO%TYPE, 
  par_NgaySinh BACSI.NGAYSINH%TYPE, par_GioiTinh BACSI.GIOITINH%TYPE, par_sdt BACSI.SDT%TYPE, 
  par_DiaChi BACSI.DIACHI%TYPE, par_ChuyenKhoa BACSI.CHUYENKHOA%TYPE)
AS
BEGIN
  UPDATE BACSI
  SET HOTEN = PAR_HOTEN, CCCD = PAR_CCCD, TRINHDO = PAR_TRINHDO, NGAYSINH = PAR_NGAYSINH, GIOITINH = PAR_GIOITINH, DIACHI = PAR_DIACHI, CHUYENKHOA = PAR_CHUYENKHOA, SDT = PAR_SDT
  WHERE MABS = PAR_MABS;
  COMMIT;
END;


/*========================= BANG LE TAN ========================*/

-- THEM LE TAN
CREATE OR REPLACE PROCEDURE INSERT_LETAN (
  PAR_USERNAME TAIKHOAN.USERNAME%TYPE, PAR_PASSWORD TAIKHOAN.PASSWORD%TYPE,
  par_HoTen LETAN.HOTEN%TYPE, par_cccd LETAN.CCCD%TYPE, par_DiaChi LETAN.DIACHI%TYPE,
  par_NgaySinh LETAN.NGAYSINH%TYPE, par_GioiTinh LETAN.GIOITINH%TYPE, par_sdt LETAN.SDT%TYPE)

AS
  V_MATKOld TAIKHOAN.MATK%TYPE;
BEGIN
    INSERT_TAIKHOAN (3, PAR_USERNAME, PAR_PASSWORD, MATK_OUT => V_MATKOld);

    INSERT INTO LETAN (MALT, MATK, CCCD, HOTEN, SDT, NGAYSINH, DIACHI, GIOITINH) 
    VALUES (SEQ4_MALT.NEXTVAL, V_MATKOld, par_cccd, par_HoTen, par_sdt, par_NgaySinh, par_DiaChi, par_GioiTinh);

    COMMIT;
END;

-- CAP NHAT LE TAN
CREATE OR REPLACE PROCEDURE UPDATE_LETAN (
  par_Malt LETAN.MALT%TYPE, par_Matk LETAN.MATK%TYPE, par_HoTen LETAN.HOTEN%TYPE, par_cccd LETAN.CCCD%TYPE,
  par_DiaChi LETAN.DIACHI%TYPE, par_NgaySinh LETAN.NGAYSINH%TYPE, par_GioiTinh LETAN.GIOITINH%TYPE, par_sdt LETAN.SDT%TYPE)
AS
BEGIN
  UPDATE LETAN
  SET HOTEN = PAR_HOTEN, CCCD = PAR_CCCD, NGAYSINH = PAR_NGAYSINH, GIOITINH = PAR_GIOITINH, DIACHI = PAR_DIACHI, SDT = PAR_SDT
  WHERE MALT = PAR_MALT;
  COMMIT;
END;


/*========================= BANG BENH NHAN ========================*/

-- THEM BENH NHAN
CREATE OR REPLACE PROCEDURE INSERT_BENHNHAN (
  par_cccd BENHNHAN.CCCD%TYPE, par_HoTen BENHNHAN.HOTEN%TYPE, par_NgaySinh BENHNHAN.NGAYSINH%TYPE, par_GioiTinh BENHNHAN.GIOITINH%TYPE,
  par_sdt BENHNHAN.SDT%TYPE, par_DiaChi BENHNHAN.DIACHI%TYPE, par_TienSuBenh BENHNHAN.TIENSUBENH%TYPE, par_DiUng BENHNHAN.DIUNG%TYPE, par_Email BENHNHAN.EMAIL%TYPE, MABN_OUT OUT BENHNHAN.MABN%TYPE)
AS
BEGIN
  INSERT INTO BENHNHAN (MABN, MATK, CCCD, HOTEN, NGAYSINH, GIOITINH, SDT, DIACHI, TIENSUBENH, DIUNG, EMAIL)
  VALUES (SEQ2_MABN.NEXTVAL, NULL, PAR_CCCD, PAR_HOTEN, PAR_NGAYSINH, PAR_GIOITINH, PAR_SDT, PAR_DIACHI, PAR_TIENSUBENH, PAR_DIUNG, PAR_EMAIL)
  RETURNING MABN INTO MABN_OUT;
  COMMIT;

END;

-- CAP NHAT BENH NHAN
CREATE OR REPLACE PROCEDURE UPDATE_BENHNHAN (
  par_Mabn BENHNHAN.MABN%TYPE, par_cccd BENHNHAN.CCCD%TYPE, par_HoTen BENHNHAN.HOTEN%TYPE, par_NgaySinh BENHNHAN.NGAYSINH%TYPE, 
  par_GioiTinh BENHNHAN.GIOITINH%TYPE, par_sdt BENHNHAN.SDT%TYPE, par_DiaChi BENHNHAN.DIACHI%TYPE, par_TienSuBenh BENHNHAN.TIENSUBENH%TYPE,
  par_DiUng BENHNHAN.DIUNG%TYPE, par_Email BENHNHAN.EMAIL%TYPE)
AS
BEGIN
  UPDATE BENHNHAN
  SET HOTEN = PAR_HOTEN, CCCD = PAR_CCCD, NGAYSINH = PAR_NGAYSINH, GIOITINH = PAR_GIOITINH, SDT = PAR_SDT, DIACHI = PAR_DIACHI, TIENSUBENH = PAR_TIENSUBENH, DIUNG = PAR_DIUNG, EMAIL = PAR_EMAIL
  WHERE MABN = PAR_MABN;
  COMMIT;
END;


/*========================= BANG PHIEUKHAM ========================*/

-- THEM PHIEU DANG KY KHAM
CREATE OR REPLACE PROCEDURE INSERT_PHIEUKHAM (
  PAR_MABN PHIEUKHAM.MABN%TYPE, PAR_MADV PHIEUKHAM.MADVK%TYPE, PAR_MABS PHIEUKHAM.MABSC%TYPE, PAR_MAPHONG PHIEUKHAM.MAPHONG%TYPE,
  PAR_MAHD PHIEUKHAM.MAHD%TYPE, PAR_NGAY_KHAM PHIEUKHAM.NGAYKHAM%TYPE, PAR_NGAY_DAT_LICH PHIEUKHAM.NGAYDATLICH%TYPE, PAR_TRANGTHAI PHIEUKHAM.TRANGTHAITH%TYPE,
  PAR_STT PHIEUKHAM.STT%TYPE, PAR_HUYETAP PHIEUKHAM.HUYETAP%TYPE, PAR_CHIEUCAO PHIEUKHAM.CHIEUCAO%TYPE, PAR_CANNANG PHIEUKHAM.CANNANG%TYPE, PAR_TRIEUCHUNG PHIEUKHAM.TRIEUCHUNGBENH%TYPE,
  PAR_LYDO PHIEUKHAM.LYDOKHAM%TYPE, PAR_TINHTRANG PHIEUKHAM.TINHTRANGCOTHE%TYPE, PAR_KETLUAN PHIEUKHAM.KETLUAN%TYPE, PAR_GIODATLICH PHIEUKHAM.GIODATLICH%TYPE,
  MAPK_OUT OUT PHIEUKHAM.MAPK%TYPE)
AS
  VAR_GIADV DICHVU.GIADV%TYPE;
BEGIN
  SELECT GIADV INTO VAR_GIADV
  FROM DICHVU d
  WHERE D.MADV = PAR_MADV;

  INSERT INTO PHIEUKHAM (MAPK, MABN, MADVK, MABSC, MAPHONG, MAHD, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN, GIADVLUCDK, GIODATLICH)
  VALUES (SEQ11_MAPK.NEXTVAL, PAR_MABN, PAR_MADV, PAR_MABS, PAR_MAPHONG, PAR_MAHD, PAR_NGAY_KHAM, PAR_NGAY_DAT_LICH, PAR_TRANGTHAI, PAR_STT, PAR_HUYETAP, PAR_LYDO, PAR_CHIEUCAO, PAR_CANNANG, PAR_TRIEUCHUNG, PAR_TINHTRANG, PAR_KETLUAN, VAR_GIADV, PAR_GIODATLICH)
  RETURNING MAPK INTO MAPK_OUT;
  COMMIT;

  UPDATE HOADON
  SET THANHTIEN = THANHTIEN + VAR_GIADV
  WHERE MAHD = PAR_MAHD;
  COMMIT;
END;

-- CAP NHAT PHIEU KHAM
CREATE OR REPLACE PROCEDURE UPDATE_PHIEUKHAM (
  PAR_MAPK PHIEUKHAM.MAPK%TYPE, PAR_HUYETAP PHIEUKHAM.HUYETAP%TYPE, PAR_CHIEUCAO PHIEUKHAM.CHIEUCAO%TYPE, PAR_CANNANG PHIEUKHAM.CANNANG%TYPE, 
  PAR_TRIEUCHUNG PHIEUKHAM.TRIEUCHUNGBENH%TYPE, PAR_TINHTRANG PHIEUKHAM.TINHTRANGCOTHE%TYPE, PAR_KETLUAN PHIEUKHAM.KETLUAN%TYPE)
AS
BEGIN

  UPDATE PHIEUKHAM
  SET TRANGTHAITH = 'Ðã hoàn thành', HUYETAP = PAR_HUYETAP, CHIEUCAO = PAR_CHIEUCAO, CANNANG = PAR_CANNANG, 
      TRIEUCHUNGBENH = PAR_TRIEUCHUNG, TINHTRANGCOTHE = PAR_TINHTRANG, KETLUAN = PAR_KETLUAN
  WHERE MAPK = PAR_MAPK;

  COMMIT;
END;


/*========================= BANG DICH VU CAN LAM SANG ========================*/
 
-- THEM KET QUA CAN LAM SAN 
CREATE OR REPLACE PROCEDURE INSERT_KETQUADVCLS (
  PAR_MAPK KETQUADICHVUCLS.MAPK%TYPE, PAR_MABS KETQUADICHVUCLS.MABSTH%TYPE, PAR_MADV KETQUADICHVUCLS.MADVCLS%TYPE,
  PAR_MAP KETQUADICHVUCLS.MAPHONG%TYPE, PAR_MAHD KETQUADICHVUCLS.MAHD%TYPE, PAR_TRANGTHAI KETQUADICHVUCLS.TRANGTHAITH%TYPE,
  PAR_STT KETQUADICHVUCLS.STT%TYPE, PAR_MOTA KETQUADICHVUCLS.MOTA%TYPE ,PAR_KETLUAN KETQUADICHVUCLS.KETLUANCLS%TYPE,
  PAR_THOIGIANTAO KETQUADICHVUCLS.THOIGIANTAO%TYPE)

AS
  VAR_GIADV DICHVU.GIADV%TYPE;
BEGIN

  SELECT GIADV INTO VAR_GIADV
  FROM DICHVU d
  WHERE D.MADV = PAR_MADV;

  INSERT INTO KETQUADICHVUCLS(MAKQ, MAPK, MABSTH, MADVCLS, MAPHONG, MAHD, TRANGTHAITH, STT, MOTA, KETLUANCLS, GIADVCLSLUCDK, THOIGIANTAO)
  VALUES (SEQ13_MAKQ.NEXTVAL, PAR_MAPK, PAR_MABS, PAR_MADV, PAR_MAP, PAR_MAHD, PAR_TRANGTHAI, PAR_STT, PAR_MOTA, PAR_KETLUAN, VAR_GIADV, PAR_THOIGIANTAO);
  COMMIT;

  UPDATE HOADON
  SET THANHTIEN = THANHTIEN + VAR_GIADV
  WHERE MAHD = PAR_MAHD;
  COMMIT;
 
END;

-- CAP NHAT THONG TIN KHONG CO ANH
CREATE OR REPLACE PROCEDURE UPDATE_KETQUADVCLS (
  PAR_MAKQ KETQUADICHVUCLS.MAKQ%TYPE, PAR_TRANGTHAI KETQUADICHVUCLS.TRANGTHAITH%TYPE, PAR_MOTA KETQUADICHVUCLS.MOTA%TYPE,
  PAR_KETLUAN KETQUADICHVUCLS.KETLUANCLS%TYPE, PAR_IMAGE KETQUADICHVUCLS.IMAGE%TYPE)
AS
BEGIN
  UPDATE KETQUADICHVUCLS 
  SET TRANGTHAITH = PAR_TRANGTHAI, MOTA = PAR_MOTA, KETLUANCLS = PAR_KETLUAN, IMAGE = PAR_IMAGE
  WHERE MAKQ = PAR_MAKQ;
  COMMIT;

END;


/*========================= BANG DON VI THuOC ========================*/

-- THEM DON VI THUOC
CREATE OR REPLACE PROCEDURE INSERT_DONVITHUOC (PAR_TENDONVI DONVITHUOC.TENDONVI%TYPE)
AS
BEGIN

  INSERT INTO DONVITHUOC (MADVT, TENDONVI, TRANGTHAI)
  VALUES (SEQ17_MADVT.NEXTVAL, PAR_TENDONVI, 1);
  COMMIT;

END;

-- CAP NHAT DON VI THUOC
CREATE OR REPLACE PROCEDURE UPDATE_DONVITHUOC (PAR_MADVT DONVITHUOC.MADVT%TYPE, PAR_TENDONVI DONVITHUOC.TENDONVI%TYPE)
AS
BEGIN
  
  UPDATE DONVITHUOC
  SET TENDONVI = PAR_TENDONVI
  WHERE MADVT = PAR_MADVT;
  COMMIT;

END;

-- XOA DON VI THUOC
CREATE OR REPLACE PROCEDURE DELETE_DONVITHUOC (PAR_MADVT DONVITHUOC.MADVT%TYPE)
AS
BEGIN
  
  UPDATE DONVITHUOC
  SET TRANGTHAI = 0
  WHERE MADVT = PAR_MADVT;
  COMMIT;

END;

/*========================= BANG HOA DON ========================*/

-- THEM HOA DON MOI
CREATE OR REPLACE PROCEDURE INSERT_HOADON (
  PAR_MALT HOADON.MALT%TYPE, PAR_MALOAIHD HOADON.MALOAIHD%TYPE, PAR_THOIDIEM HOADON.TDTT%TYPE,
  PAR_TTTT HOADON.TTTT%TYPE, PAR_THANHTIEN HOADON.THANHTIEN%TYPE, PAR_PTTT HOADON.PTTT%TYPE, MAHD_OUT OUT HOADON.MAHD%TYPE)
AS
BEGIN
  SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
  INSERT INTO HOADON (MAHD, MALT, MALOAIHD, TDTT, TTTT, THANHTIEN, PTTT)
  VALUES (SEQ16_MAHD.NEXTVAL, PAR_MALT, PAR_MALOAIHD, PAR_THOIDIEM, PAR_TTTT, PAR_THANHTIEN, PAR_PTTT)
  RETURNING MAHD INTO MAHD_OUT;
  COMMIT;

END;



-- CAP NHAT HOA DON
CREATE OR REPLACE PROCEDURE UPDATE_HOADON (
  PAR_MAHD HOADON.MAHD%TYPE, PAR_MALT HOADON.MALT%TYPE, PAR_THOIDIEM HOADON.TDTT%TYPE,
  PAR_TTTT HOADON.TTTT%TYPE, PAR_THANHTIEN HOADON.THANHTIEN%TYPE, PAR_PTTT HOADON.PTTT%TYPE)

AS
BEGIN

  UPDATE HOADON 
  SET MALT = PAR_MALT, TDTT = PAR_THOIDIEM, TTTT = PAR_TTTT, THANHTIEN = PAR_THANHTIEN, PTTT = PAR_PTTT
  WHERE MAHD = PAR_MAHD;
  COMMIT;

END;


/*========================= BANG DON THUOC ========================*/

-- THEM DON THUOC MOI_UPDATE
CREATE OR REPLACE PROCEDURE INSERT_DONTHUOC_HOADON (
  PAR_MAPK DONTHUOC.MAPK%TYPE, PAR_MALT LETAN.MALT%TYPE, PAR_GIADONTHUOC DONTHUOC.GIADT%TYPE, PAR_NGAYLAP DONTHUOC.NGAYLAP%TYPE,
  MADT_OUT OUT DONTHUOC.MADT%TYPE)

AS
  v_MAHDOld HOADON.MAHD%TYPE;

BEGIN

  SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

  INSERT_HOADON(PAR_MALT, 3, NULL, 'Chua thanh toán', 0, NULL, MAHD_OUT => v_MAHDOld);

  INSERT INTO DONTHUOC (MADT, MAHD, MAPK, GIADT, NGAYLAP)
  VALUES (SEQ12_MADT.NEXTVAL, v_MAHDOld, PAR_MAPK, PAR_GIADONTHUOC, PAR_NGAYLAP)
  RETURNING MADT INTO MADT_OUT;

  UPDATE HOADON
  SET THANHTIEN = THANHTIEN + PAR_GIADONTHUOC
  WHERE MAHD = v_MAHDOld;
  DBMS_LOCK.SLEEP(5);
  COMMIT;

END;

/*========================= BANG CTDT ========================*/

-- THEM CTDT
CREATE OR REPLACE PROCEDURE INSERT_CTDT (PAR_MADT CTDT.MADT%TYPE, PAR_MATHUOC CTDT.MATHUOC%TYPE,
  PAR_SOLANUONG CTDT.SOLANUONG%TYPE, PAR_SOLUONGUONG CTDT.SOLUONGUONG%TYPE, PAR_TRANGTHAI CTDT.TRANGTHAIDATLICH%TYPE,
  PAR_SOLUONGTHUOC CTDT.SOLUONGTHUOC%TYPE, PAR_GIABANLUCKE CTDT.GIABANLUCKE%TYPE, PAR_GHICHU CTDT.GHICHU%TYPE)
AS
  VAR_SOLUONGTHUOC NUMBER;
  VAR_SOTHUOCDALAY NUMBER := 0;
  VAR_MALOTHUOC LOTHUOC.MALOTHUOC%TYPE;
  VAR_MAHD HOADON.MAHD%TYPE;

BEGIN

  INSERT INTO CTDT (MACTDT, MADT, MATHUOC, SOLANUONG, SOLUONGUONG, TRANGTHAIDATLICH, SOLUONGTHUOC, GIABANLUCKE, GHICHU)
  VALUES (SEQ18_MACTDT.NEXTVAL, PAR_MADT, PAR_MATHUOC, PAR_SOLANUONG, PAR_SOLUONGUONG, PAR_TRANGTHAI, PAR_SOLUONGTHUOC, PAR_GIABANLUCKE, PAR_GHICHU);
  
  UPDATE DONTHUOC
  SET GIADT = GIADT + PAR_GIABANLUCKE*PAR_SOLUONGTHUOC
  WHERE MADT = PAR_MADT;

  SELECT MAHD INTO VAR_MAHD 
  FROM DONTHUOC 
  WHERE MADT = PAR_MADT;

  UPDATE HOADON 
  SET THANHTIEN = THANHTIEN + PAR_GIABANLUCKE*PAR_SOLUONGTHUOC
  WHERE MAHD = VAR_MAHD;
  
  COMMIT;
END;

/*========================= BANG NHOM ============================*/
CREATE OR REPLACE PROCEDURE INSERT_NHOM (
  PAR_TENNHOM NHOM.TENNHOM%TYPE)
AS
BEGIN
  INSERT INTO NHOM (MANHOM, TENNHOM, TRANGTHAI) 
  VALUES (SEQ19_MANHOM.NEXTVAL, PAR_TENNHOM, 1);
  COMMIT;
END;

-- CAP NHAT NHOM
CREATE OR REPLACE PROCEDURE UPDATE_NHOM (
  PAR_MANHOM NHOM.MANHOM%TYPE, PAR_TENNHOM NHOM.TENNHOM%TYPE)
AS
BEGIN
  UPDATE NHOM
  SET TENNHOM = PAR_TENNHOM
  WHERE MANHOM = PAR_MANHOM;
  
  COMMIT;
END;

-- XOA NHOM
CREATE OR REPLACE PROCEDURE DELETE_NHOM (PAR_MANHOM NHOM.MANHOM%TYPE)
AS
BEGIN

  UPDATE NHOM
  SET TRANGTHAI = 0
  WHERE MANHOM = PAR_MANHOM;
  COMMIT;

END;


/*========================= BANG LO THUOC ========================*/

-- THEM LO THUOC 
CREATE OR REPLACE PROCEDURE INSERT_LOTHUOC (
  PAR_MATHUOC LOTHUOC.MATHUOC%TYPE, PAR_NHACC LOTHUOC.NHACC%TYPE, PAR_HANSD LOTHUOC.HANSD%TYPE, PAR_SOLUONGNHAP LOTHUOC.SOLUONGNHAP%TYPE,
  PAR_GIANHAP LOTHUOC.GIANHAP%TYPE, PAR_GIABAN LOTHUOC.GIABAN%TYPE, PAR_NGAYNHAP LOTHUOC.NGAYNHAP%TYPE)

AS
BEGIN

  INSERT INTO LOTHUOC (MALOTHUOC, MATHUOC, NHACC, SOLUONGTON, HANSD, GIANHAP, NGAYNHAP, GIABAN, SOLUONGNHAP, TRANGTHAI)
  VALUES (SEQ15_MALT.NEXTVAL, PAR_MATHUOC, PAR_NHACC, PAR_SOLUONGNHAP, PAR_HANSD, PAR_GIANHAP, PAR_NGAYNHAP, PAR_GIABAN, PAR_SOLUONGNHAP, 1);

  COMMIT;

  UPDATE LOTHUOC
  SET GIABAN = PAR_GIABAN
  WHERE MATHUOC = PAR_MATHUOC;
  COMMIT;

END;

--- CAP NHAT LO THUOC
CREATE OR REPLACE PROCEDURE UPDATE_LOTHUOC (
  PAR_MALOTHUOC LOTHUOC.MALOTHUOC%TYPE, PAR_NHACC LOTHUOC.NHACC%TYPE, PAR_GIANHAP LOTHUOC.GIANHAP%TYPE,
  PAR_GIABAN LOTHUOC.GIABAN%TYPE, PAR_NGAYNHAP LOTHUOC.NGAYNHAP%TYPE)

AS
  V_MATHUOC THUOC.MATHUOC%TYPE;
BEGIN

  UPDATE LOTHUOC
  SET NHACC = PAR_NHACC, GIANHAP = PAR_GIANHAP, GIABAN = PAR_GIABAN, NGAYNHAP = PAR_NGAYNHAP
  WHERE MALOTHUOC = PAR_MALOTHUOC;
  COMMIT;

  SELECT lth.MATHUOC INTO V_MATHUOC
  FROM LOTHUOC lth
  WHERE lth.MALOTHUOC = PAR_MALOTHUOC;

  UPDATE LOTHUOC
  SET GIABAN = PAR_GIABAN
  WHERE MATHUOC = V_MATHUOC;
  COMMIT;

END;


-- XOA LO THUOC
CREATE OR REPLACE PROCEDURE DELETE_LOTHUOC (PAR_MALOTHUOC LOTHUOC.MALOTHUOC%TYPE)
AS
BEGIN

  UPDATE LOTHUOC
  SET TRANGTHAI = 0
  WHERE MALOTHUOC = PAR_MALOTHUOC;
  COMMIT;
END;

/*========================= BANG DICH VU ========================*/

-- THEM DICH VU
CREATE OR REPLACE PROCEDURE INSERT_DICHVU (
  PAR_MALOAIDV DICHVU.MALOAIDV%TYPE, PAR_TENDV DICHVU.TENDV%TYPE, PAR_GIADV DICHVU.GIADV%TYPE)

AS
BEGIN

  INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI)
  VALUES (SEQ8_MADV.NEXTVAL, PAR_MALOAIDV, PAR_TENDV, PAR_GIADV, 1);
  COMMIT;

END;

--- CAP NHAT DICH VU
CREATE OR REPLACE PROCEDURE UPDATE_DICHVU (
  PAR_MADV DICHVU.MADV%TYPE, PAR_MALOAIDV DICHVU.MALOAIDV%TYPE, PAR_TENDV DICHVU.TENDV%TYPE, PAR_GIADV DICHVU.GIADV%TYPE)

AS
BEGIN

  UPDATE DICHVU
  SET MALOAIDV = PAR_MALOAIDV, TENDV = PAR_TENDV, GIADV = PAR_GIADV
  WHERE MADV = PAR_MADV;
  COMMIT;

END;

--- XOA DICH VU
CREATE OR REPLACE PROCEDURE DELETE_DICHVU (PAR_MADV DICHVU.MADV%TYPE)
AS
BEGIN

  UPDATE DICHVU
  SET TRANGTHAI = 0
  WHERE MADV = PAR_MADV;
  COMMIT;

END;


/*========================= BANG BENH ========================*/

-- THEM BENH
CREATE OR REPLACE PROCEDURE INSERT_BENH (PAR_MAICD BENH.MAICD%TYPE, PAR_TENBENH BENH.TENBENH%TYPE)
AS
BEGIN

  INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI)
  VALUES (SEQ6_MABENH.NEXTVAL, PAR_MAICD, PAR_TENBENH, 1);
  COMMIT;

END;

-- CAP NHAT BENH
CREATE OR REPLACE PROCEDURE UPDATE_BENH (PAR_MABENH BENH.MABENH%TYPE, PAR_MAICD BENH.MAICD%TYPE, PAR_TENBENH BENH.TENBENH%TYPE)
AS
BEGIN
  
  UPDATE BENH
  SET MAICD = PAR_MAICD, TENBENH = PAR_TENBENH
  WHERE MABENH = PAR_MABENH;
  COMMIT;

END;

--- XOA BENH
CREATE OR REPLACE PROCEDURE DELETE_BENH (PAR_MABENH BENH.MABENH%TYPE)
AS
BEGIN

  UPDATE BENH
  SET TRANGTHAI = 0
  WHERE MABENH = PAR_MABENH;
  COMMIT;

END;


/*========================= BANG THUOC ========================*/

-- THEM THUOC 
CREATE OR REPLACE PROCEDURE INSERT_THUOC (
  PAR_TENTHUOC THUOC.TENTHUOC%TYPE, 
  PAR_DVT THUOC.MADVT%TYPE, 
  PAR_THANHPHAN THUOC.THANHPHAN%TYPE
)
AS
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM THUOC
  WHERE TENTHUOC = PAR_TENTHUOC;
  IF v_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Loai thuoc dã ton tai trong he thong');
  END IF;
  INSERT INTO THUOC (MATHUOC, MADVT, TENTHUOC, THANHPHAN, TRANGTHAI) 
  VALUES (SEQ14_MATHUOC.NEXTVAL, PAR_DVT, PAR_TENTHUOC, PAR_THANHPHAN, 1);
  COMMIT;
END;


-- CAP NHAT THUOC
CREATE OR REPLACE PROCEDURE UPDATE_THUOC (
  PAR_MATHUOC THUOC.MATHUOC%TYPE, PAR_TENTHUOC THUOC.TENTHUOC%TYPE, PAR_DVT THUOC.MADVT%TYPE, PAR_THANHPHAN THUOC.THANHPHAN%TYPE)
AS
BEGIN
  UPDATE THUOC
  SET MADVT = PAR_DVT, TENTHUOC = PAR_TENTHUOC, THANHPHAN = PAR_THANHPHAN
  WHERE MATHUOC = PAR_MATHUOC;
  
  COMMIT;
END;


-- XOA THUOC

CREATE OR REPLACE PROCEDURE DELETE_THUOC (PAR_MATHUOC THUOC.MATHUOC%TYPE)
AS
BEGIN  
  UPDATE THUOC
  SET TRANGTHAI = 0
  WHERE MATHUOC = PAR_MATHUOC;
  COMMIT;
END;

/*========================= BANG CHI TIET BENH ========================*/

-- THEM CHI TIET BENH
CREATE OR REPLACE PROCEDURE INSERT_CHITIETBENH (
  PAR_MAPK CHITIETBENH.MAPK%TYPE, PAR_MABENH CHITIETBENH.MABENH%TYPE)
AS
BEGIN
  INSERT INTO CHITIETBENH (MAPK, MABENH)
  VALUES (PAR_MAPK, PAR_MABENH);
  
  COMMIT;
END;


-- THEM LOAI DICH VU 
CREATE OR REPLACE PROCEDURE INSERT_LOAIDICHVU (
  PAR_TENLOAIDV LOAIDV.TENLOAIDV%TYPE)
AS
BEGIN

  INSERT INTO LOAIDV (MALOAIDV, TENLOAIDV, TRANGTHAI) 
  VALUES (SEQ9_MALDV.NEXTVAL, PAR_TENLOAIDV, 1);
  COMMIT;

END;

-- CAP NHAT LOAI DICH VU
CREATE OR REPLACE PROCEDURE UPDATE_LOAIDICHVU (
  PAR_MALOAIDV LOAIDV.MALOAIDV%TYPE, PAR_TENLOAIDV LOAIDV.TENLOAIDV%TYPE)
AS
BEGIN
  UPDATE LOAIDV
  SET TENLOAIDV = PAR_TENLOAIDV
  WHERE MALOAIDV = PAR_MALOAIDV;
  
  COMMIT;
END;

-- XOA LOAI DICH VU
CREATE OR REPLACE PROCEDURE DELETE_LOAIDICHVU (PAR_MALOAIDV LOAIDV.MALOAIDV%TYPE)
AS
BEGIN

  UPDATE LOAIDV
  SET TRANGTHAI = 0
  WHERE MALOAIDV = PAR_MALOAIDV;
  COMMIT;

END;


/*========================= BANG PHAN CONG KHAM ========================*/
-- THEM LICH PHAN CONG
CREATE OR REPLACE PROCEDURE INSERT_PHANCONGKHAM (
  PAR_MABS PHANCONGKHAM.MABS%TYPE, PAR_THU PHANCONGKHAM.THU%TYPE, 
  PAR_GIOBATDAU PHANCONGKHAM.GIOBATDAU%TYPE, PAR_GIOKETTHUC PHANCONGKHAM.GIOKETTHUC%TYPE
)
AS
BEGIN
  INSERT INTO PHANCONGKHAM (MABS, THU, GIOBATDAU, GIOKETTHUC)
  VALUES (PAR_MABS, PAR_THU, PAR_GIOBATDAU, PAR_GIOKETTHUC);
  COMMIT;
END;

-- SUA LICH PHAN CONG
CREATE OR REPLACE PROCEDURE UPDATE_PHANCONGKHAM (
  PAR_MABS PHANCONGKHAM.MABS%TYPE, PAR_THU PHANCONGKHAM.THU%TYPE,
  PAR_GIOBATDAU PHANCONGKHAM.GIOBATDAU%TYPE, PAR_GIOKETTHUC PHANCONGKHAM.GIOKETTHUC%TYPE
)
AS
BEGIN
  UPDATE PHANCONGKHAM
  SET THU = PAR_THU, GIOBATDAU = PAR_GIOBATDAU, GIOKETTHUC = PAR_GIOKETTHUC
  WHERE MABS = PAR_MABS;
  COMMIT;

END;


/*========================= BANG GIO DAT LICH ========================*/
CREATE OR REPLACE PROCEDURE INSERT_GIODATLICH (
  PAR_MACTDT GIODATLICH.MACTDT%TYPE, PAR_THOIGIAN GIODATLICH.THOIGIAN%TYPE
)
AS
BEGIN
  INSERT INTO GIODATLICH (MAGIO, MACTDT, THOIGIAN)
  VALUES (SEQ20_MAGIO.NEXTVAL, PAR_MACTDT, PAR_THOIGIAN);

  UPDATE CTDT SET TRANGTHAIDATLICH = 'Ðã d?t l?ch' WHERE MACTDT = PAR_MACTDT;
  COMMIT;

END;

CREATE OR REPLACE PROCEDURE DELETE_GIODATLICH (
  PAR_MACTDT GIODATLICH.MACTDT%TYPE)
AS
BEGIN
  DELETE FROM GIODATLICH WHERE MACTDT = PAR_MACTDT;

  UPDATE CTDT SET TRANGTHAIDATLICH = 'Chua d?t l?ch' WHERE MACTDT = PAR_MACTDT;
  COMMIT;

END;
/*========================= PROCEDURE CHO MOBILE ========================*/

CREATE OR REPLACE PROCEDURE INSERT_TAIKHOAN_BENHNHAN (
  PAR_USERNAME TAIKHOAN.USERNAME%TYPE, PAR_PASSWORD TAIKHOAN.PASSWORD%TYPE, PAR_CCCD BENHNHAN.CCCD%TYPE, PAR_HOTEN BENHNHAN.HOTEN%TYPE, PAR_NGAYSINH BENHNHAN.NGAYSINH%TYPE, PAR_GIOITINH BENHNHAN.GIOITINH%TYPE,
  PAR_SDT BENHNHAN.SDT%TYPE, PAR_DIACHI BENHNHAN.DIACHI%TYPE, PAR_TIENSUBENH BENHNHAN.TIENSUBENH%TYPE, PAR_DIUNG BENHNHAN.DIUNG%TYPE, PAR_EMAIL BENHNHAN.EMAIL%TYPE, MABN_OUT OUT BENHNHAN.MABN%TYPE)
AS
  V_MATKOld TAIKHOAN.MATK%TYPE;
BEGIN
  INSERT_TAIKHOAN (4, PAR_USERNAME, PAR_PASSWORD, MATK_OUT => V_MATKOld);

  INSERT INTO BENHNHAN (MABN, MATK, CCCD, HOTEN, NGAYSINH, GIOITINH, SDT, DIACHI, TIENSUBENH, DIUNG, EMAIL)
  VALUES (SEQ2_MABN.NEXTVAL, V_MATKOld, PAR_CCCD, PAR_HOTEN, PAR_NGAYSINH, PAR_GIOITINH, PAR_SDT, PAR_DIACHI, PAR_TIENSUBENH, PAR_DIUNG, PAR_EMAIL)
  RETURNING MABN INTO MABN_OUT;
  COMMIT;

END;

CREATE OR REPLACE PROCEDURE INSERT_TAIKHOAN_UPDATE_BENHNHAN (
  PAR_USERNAME TAIKHOAN.USERNAME%TYPE, PAR_PASSWORD TAIKHOAN.PASSWORD%TYPE, PAR_MABN BENHNHAN.MABN%TYPE, PAR_CCCD BENHNHAN.CCCD%TYPE, PAR_HOTEN BENHNHAN.HOTEN%TYPE, PAR_NGAYSINH BENHNHAN.NGAYSINH%TYPE, PAR_GIOITINH BENHNHAN.GIOITINH%TYPE,
  PAR_SDT BENHNHAN.SDT%TYPE, PAR_DIACHI BENHNHAN.DIACHI%TYPE, PAR_TIENSUBENH BENHNHAN.TIENSUBENH%TYPE, PAR_DIUNG BENHNHAN.DIUNG%TYPE, MABN_OUT OUT BENHNHAN.MABN%TYPE)
AS
  V_MATKOld TAIKHOAN.MATK%TYPE;
BEGIN
  INSERT_TAIKHOAN (4, PAR_USERNAME, PAR_PASSWORD, MATK_OUT => V_MATKOld);

  UPDATE BENHNHAN 
  SET MATK = V_MATKOld, CCCD = PAR_CCCD, HOTEN = PAR_HOTEN, NGAYSINH = PAR_NGAYSINH, GIOITINH = PAR_GIOITINH, SDT = PAR_SDT, DIACHI = PAR_DIACHI, TIENSUBENH = PAR_TIENSUBENH, DIUNG = PAR_DIUNG
  WHERE MABN = PAR_MABN
  RETURNING MABN INTO MABN_OUT;
  COMMIT;

END;

/*========================= PROCEDURE THONG KE ========================*/

-- THONG KE DOANH THU MOI THANG
CREATE OR REPLACE PROCEDURE GET_DOANHTHU (PAR_MONTH IN NUMBER, PAR_YEAR IN NUMBER, cursor OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN cursor FOR
      SELECT L.MALOAIHD, L.TENLOAIHD, SUM(H.THANHTIEN)
      FROM HOADON H
      JOIN LOAIHD L ON L.MALOAIHD = H.MALOAIHD
      WHERE EXTRACT(YEAR FROM TDTT) = PAR_YEAR AND EXTRACT(MONTH FROM TDTT) = PAR_MONTH
      GROUP BY L.MALOAIHD, L.TENLOAIHD;
END;


-- THONG KE LUONG THUOC NHAP MOI THANG
CREATE OR REPLACE PROCEDURE GET_LUONGTHUOCNHAP (PAR_MONTH IN NUMBER, PAR_YEAR IN NUMBER, cursor OUT SYS_REFCURSOR)
AS
BEGIN
  OPEN cursor FOR
    SELECT T.MATHUOC, T.TENTHUOC, SUM(SOLUONGTON)
    FROM LOTHUOC l
    JOIN THUOC t ON T.MATHUOC = L.MATHUOC
    WHERE EXTRACT(MONTH FROM L.NGAYNHAP) = PAR_MONTH AND EXTRACT(YEAR FROM L.NGAYNHAP) = PAR_YEAR
    GROUP BY T.MATHUOC, T.TENTHUOC;

  COMMIT;
END;

-- 
CREATE OR REPLACE FUNCTION TINH_KHOANG_CACH_KHAM_TRUNG_BINH(ma_benh_nhan IN NUMBER) RETURN NUMBER IS
    tong_khoang_cach NUMBER := 0;
    so_lan_kham NUMBER := 0;
    thang_truoc DATE;
BEGIN
    FOR r IN (SELECT NGAYKHAM FROM PHIEUKHAM WHERE MABN = ma_benh_nhan ORDER BY NGAYKHAM) LOOP
        IF so_lan_kham > 0 THEN
            tong_khoang_cach := tong_khoang_cach + (r.NGAYKHAM - thang_truoc);
        END IF;
        thang_truoc := r.NGAYKHAM;
        so_lan_kham := so_lan_kham + 1;
    END LOOP;
    
    IF so_lan_kham > 1 THEN
        RETURN ROUND(tong_khoang_cach / (so_lan_kham - 1));
    ELSE
        RETURN 0;
    END IF;
END;
/
