-- DANH SACH TRIGGER

-- Mỗi ngày khám tối đa n bệnh nhân (PHIEUKHAM)
CREATE OR REPLACE TRIGGER TRIGGER_SOBENHNHANTOIDA_PHIEUKHAM
BEFORE INSERT ON PHIEUKHAM
FOR EACH ROW
DECLARE
  VAR_SOBENHNHAN NUMBER;
  VAR_NGAYKHAM DATE;
  VAR_SOTOIDA NUMBER := 5;
BEGIN
  VAR_NGAYKHAM := TRUNC(SYSDATE);

  SELECT COUNT(*) INTO VAR_SOBENHNHAN 
  FROM PHIEUKHAM
  WHERE TRUNC(NGAYKHAM) = VAR_NGAYKHAM;

  IF VAR_SOBENHNHAN >= VAR_SOTOIDA THEN
    RAISE_APPLICATION_ERROR(-20001, 'Số lượng phiếu khám đã được tạo trong ngày đã vượt quá ngưỡng tối đa.');
  END IF;
END;

SELECT * FROM PHIEUKHAM
INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (12, 3, 3, 1, 3, 3, TO_DATE('2024-04-25', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 3, 140, 'Mệt mỏi', 180, 70, 'Nhuc chan', 'Bình thường', 'Không ghi chú');
COMMIT;
INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (13, 3, 3, 3, 3, 3, TO_DATE('2024-04-25', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 3, 140, 'Mệt mỏi', 180, 70, 'Nhuc chan', 'Bình thường', 'Không ghi chú');
COMMIT;
INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (14, 3, 3, 3, 3, 3, TO_DATE('2024-04-25', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 3, 140, 'Mệt mỏi', 180, 70, 'Nhuc chan', 'Bình thường', 'Không ghi chú');
COMMIT;
INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (15, 3, 3, 3, 3, 3, TO_DATE('2024-04-25', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 3, 140, 'Mệt mỏi', 180, 70, 'Nhuc chan', 'Bình thường', 'Không ghi chú');
COMMIT;
INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (16, 3, 3, 3, 3, 3, TO_DATE('2024-04-25', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 3, 140, 'Mệt mỏi', 180, 70, 'Nhuc chan', 'Bình thường', 'Không ghi chú');
COMMIT;
INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (17, 3, 3, 3, 3, 3, TO_DATE('2024-04-25', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 3, 140, 'Mệt mỏi', 180, 70, 'Nhuc chan', 'Bình thường', 'Không ghi chú');
COMMIT;


SELECT * FROM CTDT



-- Khi kê thuốc xong thì cập nhập lại số lượng thuốc tồn trong kho (CTDT, THUOC)
