-- ADD KHOA NGOAI
ALTER TABLE BENHNHAN ADD CONSTRAINT FK_BENHNHAN_TAIKHOAN_01 FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK);
ALTER TABLE BACSI ADD CONSTRAINT FK_BACSI_TAIKHOAN_02 FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK);
ALTER TABLE LETAN ADD CONSTRAINT FK_LETAN_TAIKHOAN_03 FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK);
ALTER TABLE DICHVU ADD CONSTRAINT FK_DICHVU_LOAIDV_04 FOREIGN KEY(MALOAIDV) REFERENCES LOAIDV(MALOAIDV);
ALTER TABLE PHIEUKHAM ADD CONSTRAINT FK_PHIEUKHAM_BENHNHAN_05 FOREIGN KEY(MABN) REFERENCES BENHNHAN(MABN);
ALTER TABLE PHIEUKHAM ADD CONSTRAINT FK_PHIEUKHAM_BACSI_06 FOREIGN KEY(MABSC) REFERENCES BACSI(MABS);
ALTER TABLE PHIEUKHAM ADD CONSTRAINT FK_PHIEUKHAM_DICHVU_07 FOREIGN KEY(MADVK) REFERENCES DICHVU(MADV);
ALTER TABLE PHIEUKHAM ADD CONSTRAINT FK_PHIEUKHAM_HOADON_08 FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD);
ALTER TABLE PHIEUKHAM ADD CONSTRAINT FK_PHIEUKHAM_PHONG_09 FOREIGN KEY(MAPHONG) REFERENCES PHONGKHAM(MAPHONG);
ALTER TABLE KETQUADICHVUCLS ADD CONSTRAINT FK_DVCLS_PHIEUKHAM_10 FOREIGN KEY(MAPK) REFERENCES PHIEUKHAM(MAPK);
ALTER TABLE KETQUADICHVUCLS ADD CONSTRAINT FK_DVCLS_BACSI_11 FOREIGN KEY(MABSTH) REFERENCES BACSI(MABS);
ALTER TABLE KETQUADICHVUCLS ADD CONSTRAINT FK_DVCLS_DICHVU_12 FOREIGN KEY(MADVCLS) REFERENCES DICHVU(MADV);
ALTER TABLE KETQUADICHVUCLS ADD CONSTRAINT FK_DVCLS_PHONG_13 FOREIGN KEY(MAPHONG) REFERENCES PHONGKHAM(MAPHONG);
ALTER TABLE KETQUADICHVUCLS ADD CONSTRAINT FK_DVCLS_HOADON_14 FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD);
ALTER TABLE CHITIETBENH ADD CONSTRAINT FK_CTBENH_PHIEUKHAM_15 FOREIGN KEY(MAPK) REFERENCES PHIEUKHAM(MAPK);
ALTER TABLE CHITIETBENH ADD CONSTRAINT FK_CTBENH_BENH_16 FOREIGN KEY(MABENH) REFERENCES BENH(MABENH);
ALTER TABLE DONTHUOC ADD CONSTRAINT FK_DONTHUOC_HOADON_17 FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD);
ALTER TABLE DONTHUOC ADD CONSTRAINT FK_DONTHUOC_PHIEUKHAM_18 FOREIGN KEY(MAPK) REFERENCES PHIEUKHAM(MAPK);
ALTER TABLE CTDT ADD CONSTRAINT FK_CTDT_DONTHUOC_19 FOREIGN KEY(MADT) REFERENCES DONTHUOC(MADT);
ALTER TABLE CTDT ADD CONSTRAINT FK_CTDT_THUOC_20 FOREIGN KEY(MATHUOC) REFERENCES THUOC(MATHUOC);
ALTER TABLE THUOC ADD CONSTRAINT FK_THUOC_DONVITHUOC_21 FOREIGN KEY(MADVT) REFERENCES DONVITHUOC(MADVT);
ALTER TABLE LOTHUOC ADD CONSTRAINT FK_LOTHUOC_THUOC_22 FOREIGN KEY(MATHUOC) REFERENCES THUOC(MATHUOC);
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_LETAN_23 FOREIGN KEY(MALT) REFERENCES LETAN(MALT);
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_LOAIHOADON_24 FOREIGN KEY(MALOAIHD) REFERENCES LOAIHD(MALOAIHD);
ALTER TABLE TAIKHOAN ADD CONSTRAINT FK_TAIKHOAN_NHOM_25 FOREIGN KEY(MANHOM) REFERENCES NHOM(MANHOM);
ALTER TABLE NHOM_VAITRO ADD CONSTRAINT FK_NHOM_26 FOREIGN KEY(MANHOM) REFERENCES NHOM(MANHOM);
ALTER TABLE NHOM_VAITRO ADD CONSTRAINT FK_VAITRO_26 FOREIGN KEY(MAVAITRO) REFERENCES VAITRO(MAVAITRO);

-- DROP KHOA NGOAI
ALTER TABLE BENHNHAN DROP CONSTRAINT FK_BENHNHAN_TAIKHOAN_01;
ALTER TABLE BACSI DROP CONSTRAINT FK_BACSI_TAIKHOAN_02;
ALTER TABLE LETAN DROP CONSTRAINT FK_LETAN_TAIKHOAN_03;
ALTER TABLE DICHVU DROP CONSTRAINT FK_DICHVU_LOAIDV_04;
ALTER TABLE PHIEUKHAM DROP CONSTRAINT FK_PHIEUKHAM_BENHNHAN_05;
ALTER TABLE PHIEUKHAM DROP CONSTRAINT FK_PHIEUKHAM_BACSI_06;
ALTER TABLE PHIEUKHAM DROP CONSTRAINT FK_PHIEUKHAM_DICHVU_07;
ALTER TABLE PHIEUKHAM DROP CONSTRAINT FK_PHIEUKHAM_HOADON_08;
ALTER TABLE PHIEUKHAM DROP CONSTRAINT FK_PHIEUKHAM_PHONG_09;
ALTER TABLE KETQUADICHVUCLS DROP CONSTRAINT FK_DVCLS_PHIEUKHAM_10;
ALTER TABLE KETQUADICHVUCLS DROP CONSTRAINT FK_DVCLS_BACSI_11;
ALTER TABLE KETQUADICHVUCLS DROP CONSTRAINT FK_DVCLS_DICHVU_12;
ALTER TABLE KETQUADICHVUCLS DROP CONSTRAINT FK_DVCLS_PHONG_13;
ALTER TABLE KETQUADICHVUCLS DROP CONSTRAINT FK_DVCLS_HOADON_14;
ALTER TABLE CHITIETBENH DROP CONSTRAINT FK_CTBENH_PHIEUKHAM_15;
ALTER TABLE CHITIETBENH DROP CONSTRAINT FK_CTBENH_BENH_16;
ALTER TABLE DONTHUOC DROP CONSTRAINT FK_DONTHUOC_HOADON_17;
ALTER TABLE DONTHUOC DROP CONSTRAINT FK_DONTHUOC_PHIEUKHAM_18;
ALTER TABLE CTDT DROP CONSTRAINT FK_CTDT_DONTHUOC_19;
ALTER TABLE CTDT DROP CONSTRAINT FK_CTDT_THUOC_20;
ALTER TABLE THUOC DROP CONSTRAINT FK_THUOC_DONVITHUOC_21;
ALTER TABLE LOTHUOC DROP CONSTRAINT FK_LOTHUOC_THUOC_22;
ALTER TABLE HOADON DROP CONSTRAINT FK_HOADON_LETAN_23;
ALTER TABLE HOADON DROP CONSTRAINT FK_HOADON_LOAIHOADON_24;
ALTER TABLE TAIKHOAN DROP CONSTRAINT FK_TAIKHOAN_NHOM_25;
ALTER TABLE NHOM_VAITRO DROP CONSTRAINT FK_NHOM_26;
ALTER TABLE NHOM_VAITRO DROP CONSTRAINT FK_VAITRO_26;

/* ======================== CAC RANG BUOC TOAN VEN ======================== */

-- TRINHDO là 'Thạc sĩ', 'Tiến sĩ', 'CK1', 'CK2'
ALTER TABLE BACSI 
ADD CONSTRAINT CHECK_TRINHDO_BACSI CHECK (TRINHDO IN ('Thạc sĩ', 'Tiến sĩ', 'CK1', 'CK2'));

ALTER TABLE BACSI 
DROP CONSTRAINT CHECK_TRINHDO_BACSI;


-- GIOITINH Là 'Nam', 'Nu', 'Khac'
ALTER TABLE LETAN 
ADD CONSTRAINT CHECK_GIOITINH_LETAN CHECK (GIOITINH IN ('Nam', 'Nữ', 'Khác'));
ALTER TABLE BACSI 
ADD CONSTRAINT CHECK_GIOITINH_BACSI CHECK (GIOITINH IN ('Nam', 'Nữ', 'Khác'));
ALTER TABLE BENHNHAN 
ADD CONSTRAINT CHECK_GIOITINH_BENHNHAN CHECK (GIOITINH IN ('Nam', 'Nữ', 'Khác'));


-- NGAYDATLICH <= NGAYKHAM
ALTER TABLE PHIEUKHAM 
ADD CONSTRAINT CHECK_PHIEUKHAM_NGAYKHAM_NGAYDATLICH CHECK (NGAYKHAM >= NGAYDATLICH);


-- Giá bán thuốc phải cao hơn giá nhập (LOTHUOC)
ALTER TABLE LOTHUOC
ADD CONSTRAINT CHECK_GIABAN_GIANHAP CHECK (GIABAN > GIANHAP);