/* ======================== INSERT DU LIEU ======================== */

-- INSERT INTO THAMSO
DELETE FORM THAMSO;

INSERT INTO THAMSO (TENTHAMSO, GIATRI) VALUES ('SoLuongKhamToiDa', 30);
COMMIT;

-- INSERT INTO TAIKHOAN
DELETE FROM TAIKHOAN;

INSERT INTO TAIKHOAN (MATK, MANHOM, USERNAME, PASSWORD, TRANGTHAI) VALUES (1, 1, 'Administrator', '$2a$10$7cEO49CDMku0KntvXCX.zuvsNU8CbmYN2wkSOvaOdKqCuFpQYJyZC', 1);
INSERT INTO TAIKHOAN (MATK, MANHOM, USERNAME, PASSWORD, TRANGTHAI) VALUES (SEQ3_MATK.NEXTVAL, 2, 'user2', '$2a$10$7cEO49CDMku0KntvXCX.zu7dMEmRpR5u8y05hPdNl1oLqpsvJIL4q', 1);
COMMIT;


-- INSERT INTO VAITRO
DELETE FROM VAITRO;
-- /benhnhan/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benhnhan/getAll', 'Lấy danh sách bệnh nhân');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benhnhan/insert', 'Thêm bệnh nhân');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benhnhan/getById', 'Lấy thông tin một bệnh nhân qua ID');
-- /bacsi/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/bacsi/getAll', 'lấy danh sách bác sĩ');
-- /account/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/getAllUserGroup', 'lấy danh sách nhóm người dùng');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/getAllAccount', 'lấy danh sách tài khoản');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/insert', 'thêm tài khoản');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/updateTTCN', 'cập nhật thông tin cá nhân');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/updateTTTK', 'cập nhật thông tin tài khoản');
-- /dichvu/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dichvu/getAllLDV', 'lấy danh sách dịch vụ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dichvu/getAll', 'lấy danh sách dịch vụ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dichvu/insert', 'thêm dịch vụ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dichvu/update', 'cập nhật dịch vụ');
-- /benh/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benh/getAll', 'lấy danh sách bệnh');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benh/insert', 'thêm bệnh');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benh/update', 'cập nhật bệnh');
-- /don vi thuoc/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dvt/getAll', 'lấy danh sách đơn vị thuốc');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dvt/insert', 'thêm đơn vị thuốc');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dvt/update', 'cập nhật đơn vị thuốc');
-- /admin/ (admin sửa thamso)
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/admin/getThamSo', 'lấy tham số');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/admin/updateThamSo', 'cập nhật tham số');
-- /role/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/getAll', 'lấy danh sách quyền');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/getById', 'lấy danh sách quyền theo ID');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/insert', 'thêm quyền');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/update', 'cập nhật quyền');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/delete', 'xóa quyền');
-- /phieukham/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/insert-pk', 'them phieu kham');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/insert-bn-pk', 'them benh nhan va phieu kham');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/insert-just-pk', 'them chi phieu kham');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/dsdk', 'lay danh sach dang ki');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/chitiet-pk/getById', 'lay chi tiet cua mot phieu kham');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/dspk/getById', 'lay chi tiet cua mot phieu kham');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/ds-benh/getById', 'lay benh cua phieu kham');
-- /donthuoc/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/donthuoc/insert', 'them don thuoc moi');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/donthuoc/insert-ctdt', 'them ctdt don thuoc moi');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/donthuoc/ds-thuoc/getById', 'lay thuoc cua mot don thuoc');
-- /thuoc/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thuoc/getAll', 'lay danh sach tat ca thuoc trong kho');
-- /hoadon/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/hoadon/insert', 'them hoa don');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/hoadon/dshd/getById', 'them hoa don');
-- /can lam san/
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/cls/ds-cls/getById', 'them hoa don');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/cls/getAll', 'them hoa don');
COMMIT;



-- INSERT INTO NHOM_VAITRO
DELETE FROM NHOM_VAITRO;

INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 100);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 101);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 102);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 103);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 104);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 105);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 106);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 107);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 108);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 109);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 110);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 111);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 112);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 113);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 114);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 115);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 116);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 117);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 118);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 119);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 120);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 121);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 122);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 123);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 124);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 125);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 126);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 127);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 128);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 129);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 130);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 131);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 132);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 133);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 134);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 135);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 136);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 137);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 138);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 139);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 140);
COMMIT;

-- INSERT INTO BENHNHAN
INSERT INTO BENHNHAN (MABN, MATK, CCCD, HOTEN, NGAYSINH, GIOITINH, SDT, DIACHI, TIENSUBENH, DIUNG) VALUES (SEQ2_MABN.NEXTVAL, 1, 'CCCD1', 'Nguyễn Văn A', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'Nam', '0123456789', '123 Đường ABC', 'Tiền sử bệnh 1', 'Dị ứng thuốc 1');
INSERT INTO BENHNHAN (MABN, MATK, CCCD, HOTEN, NGAYSINH, GIOITINH, SDT, DIACHI, TIENSUBENH, DIUNG) VALUES (SEQ2_MABN.NEXTVAL, 2, 'CCCD2', 'Trần Thị B', TO_DATE('1985-05-05', 'YYYY-MM-DD'), 'Nữ', '0987654321', '456 Đường XYZ', 'Tiền sử bệnh 2', 'Dị ứng thuốc 2');
INSERT INTO BENHNHAN (MABN, MATK, CCCD, HOTEN, NGAYSINH, GIOITINH, SDT, DIACHI, TIENSUBENH, DIUNG) VALUES (SEQ2_MABN.NEXTVAL, 3, 'CCCD3', 'Lê Văn C', TO_DATE('2000-10-10', 'YYYY-MM-DD'), 'Nam', '0369852147', '789 Đường LMN', 'Tiền sử bệnh 3', 'Dị ứng thuốc 3');
COMMIT;

-- INSERT INTO BACSI
DELETE FROM BACSI;

INSERT INTO BACSI (MABS, MATK, CCCD, HOTEN, TRINHDO, GIOITINH, SDT, NGAYSINH, DIACHI, CHUYENKHOA) VALUES (100, 4, 'CCCD4', 'Phạm Thị BCareFull', 'Tiến sĩ', 'Nữ', '0369852147', TO_DATE('1980-02-15', 'YYYY-MM-DD'), '789 Đường KLM', 'Chuyên khoa 1');
COMMIT;

-- INSERT INTO LETAN
DELETE FROM LETAN;

-- INSERT INTO PHONGKHAM
DELETE FROM PHONGKHAM;

INSERT INTO PHONGKHAM (MAPHONG, TENPHONG, SOPHONG, TANG) VALUES (SEQ5_MAPHONG.NEXTVAL, 'Phòng khám 1', 10, 1);
INSERT INTO PHONGKHAM (MAPHONG, TENPHONG, SOPHONG, TANG) VALUES (SEQ5_MAPHONG.NEXTVAL, 'Phòng khám 2', 8, 2);
INSERT INTO PHONGKHAM (MAPHONG, TENPHONG, SOPHONG, TANG) VALUES (SEQ5_MAPHONG.NEXTVAL, 'Phòng khám 3', 12, 3);
COMMIT;

-- INSERT INTO BENH
DELETE FROM BENH;

INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'C16', 'U ác của dạ dày', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'M16', 'Thoái hóa khớp háng', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'A30', 'Bệnh phong [bệnh Hansen]', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'I63', 'Nhồi máu não', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'B90', 'Di chứng do lao', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'R05', 'Ho', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'R15', 'Ỉa không kiểm soát', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'I67.2', 'Xơ vữa động mạch não', 1);
COMMIT;

-- INSERT INTO LOAIHD
DELETE FROM LOAIHD;

INSERT INTO LOAIHD (MALOAIHD, TENLOAIHD) VALUES (SEQ7_MALHD.NEXTVAL, 'Hóa đơn khám');
INSERT INTO LOAIHD (MALOAIHD, TENLOAIHD) VALUES (SEQ7_MALHD.NEXTVAL, 'Hóa đơn dịch vụ CLS');
INSERT INTO LOAIHD (MALOAIHD, TENLOAIHD) VALUES (SEQ7_MALHD.NEXTVAL, 'Hóa đơn thuốc');
COMMIT;

-- INSERT INTO LOAIDV
DELETE FROM LOAIDV;

INSERT INTO LOAIDV (MALOAIDV, TENLOAIDV) VALUES (SEQ9_MALDV.NEXTVAL, 'Thông thường');
INSERT INTO LOAIDV (MALOAIDV, TENLOAIDV) VALUES (SEQ9_MALDV.NEXTVAL, 'Cận lâm sàn');
INSERT INTO LOAIDV (MALOAIDV, TENLOAIDV) VALUES (SEQ9_MALDV.NEXTVAL, 'Đặc biệt');
COMMIT;


-- INSERT INTO DICHVU
DELETE FROM DICHVU;

INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 2, 'Đo điện não', 100000, 1);
INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 2, 'Chụp X-Quang', 200000, 1);
INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 1, 'Thăm khám tại phòng mạch', 300000, 1);
INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 2, 'Xét nghiệm máu', 100000, 1);
INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 3, 'Fix bug hộ', 200000, 1);
INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 3, 'Chữa tâm thần', 300000, 1);
COMMIT;

-- INSERT INTO PHIEUKHAM
DELETE FROM PHIEUKHAM;

INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (SEQ11_MAPK.NEXTVAL, SEQ2_MABN.NEXTVAL, 100, 101, SEQ16_MAHD.NEXTVAL, SEQ5_MAPHONG.NEXTVAL, TO_DATE('2024-04-19', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 1, 120, 'Đau đầu', 170, 60, 'Đau nữa đầu', 'Bình thường', 'Không ghi chú');
INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (SEQ11_MAPK.NEXTVAL, SEQ2_MABN.NEXTVAL, 100, 102, SEQ16_MAHD.NEXTVAL, SEQ5_MAPHONG.NEXTVAL, TO_DATE('2024-04-20', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 2, 130, 'Đau bụng', 160, 50, 'Đau cu', 'Bình thường', 'Không ghi chú');
INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (SEQ11_MAPK.NEXTVAL, SEQ2_MABN.NEXTVAL, 100, 103, SEQ16_MAHD.NEXTVAL, SEQ5_MAPHONG.NEXTVAL, TO_DATE('2024-04-21', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 3, 140, 'Mệt mỏi', 180, 70, 'Đau chân', 'Bình thường', 'Không ghi chú');
COMMIT;

-- INSERT INTO KETQUADICHVUCLS
DELETE FROM KETQUADICHVUCLS;

INSERT INTO KETQUADICHVUCLS (MAKQ, MAPK, MABSTH, MADVCLS, MAPHONG, MAHD, TRANGTHAITH, STT, KETLUANCLS) VALUES (SEQ13_MAKQ.NEXTVAL, 100, 100, 101, 100, 100, 'Đã thực hiện', 1, 'Kết luận 1');
INSERT INTO KETQUADICHVUCLS (MAKQ, MAPK, MABSTH, MADVCLS, MAPHONG, MAHD, TRANGTHAITH, STT, KETLUANCLS) VALUES (SEQ13_MAKQ.NEXTVAL, 101, 100, 101, 101, 101, 'Đã thực hiện', 2, 'Kết luận 2');
INSERT INTO KETQUADICHVUCLS (MAKQ, MAPK, MABSTH, MADVCLS, MAPHONG, MAHD, TRANGTHAITH, STT, KETLUANCLS) VALUES (SEQ13_MAKQ.NEXTVAL, 102, 100, 101, 102, 102, 'Đã thực hiện', 3, 'Kết luận 3');
COMMIT;

-- INSERT INTO CHITIETBENH
DELETE FROM CHITIETBENH;

INSERT INTO CHITIETBENH (MAPK, MABENH) VALUES (100, 100);
INSERT INTO CHITIETBENH (MAPK, MABENH) VALUES (101, 102);
INSERT INTO CHITIETBENH (MAPK, MABENH) VALUES (102, 106);
COMMIT;

-- INSERT INTO HOADON
DELETE FROM HOADON;

INSERT INTO HOADON (MAHD, MALT, MALOAIHD, TDTT, TTTT, THANHTIEN, PTTT) VALUES (SEQ16_MAHD.NEXTVAL, 1, 100, TO_DATE('2024-04-19', 'YYYY-MM-DD'), 'Đã thanh toán', 150000, 'Tiền mặt');
INSERT INTO HOADON (MAHD, MALT, MALOAIHD, TDTT, TTTT, THANHTIEN, PTTT) VALUES (SEQ16_MAHD.NEXTVAL, 1, 101, TO_DATE('2024-04-20', 'YYYY-MM-DD'), 'Đã thanh toán', 200000, 'Thẻ thanh toán');
INSERT INTO HOADON (MAHD, MALT, MALOAIHD, TDTT, TTTT, THANHTIEN, PTTT) VALUES (SEQ16_MAHD.NEXTVAL, 1, 102, TO_DATE('2024-04-21', 'YYYY-MM-DD'), 'Chưa thanh toán', 300000, 'Chuyển khoản');
COMMIT;

-- INSERT INTO THUOC
DELETE FROM THUOC;

INSERT INTO THUOC (MATHUOC, MADVT, TENTHUOC, THANHPHAN) VALUES (SEQ14_MATHUOC.NEXTVAL, 100, 'Chlorpromazin', 'Thành phần 1');
INSERT INTO THUOC (MATHUOC, MADVT, TENTHUOC, THANHPHAN) VALUES (SEQ14_MATHUOC.NEXTVAL, 101, 'Morphin', 'Thành phần 2');
INSERT INTO THUOC (MATHUOC, MADVT, TENTHUOC, THANHPHAN) VALUES (SEQ14_MATHUOC.NEXTVAL, 102, 'Insulin', 'Thành phần 3');
COMMIT;

-- INSERT INTO DONVITHUOC
DELETE FROM DONVITHUOC;

INSERT INTO DONVITHUOC (MADVT, TENDONVI, TRANGTHAI) VALUES (SEQ17_MADVT.NEXTVAL, 'Viên', 1);
INSERT INTO DONVITHUOC (MADVT, TENDONVI, TRANGTHAI) VALUES (SEQ17_MADVT.NEXTVAL, 'Ống', 1);
INSERT INTO DONVITHUOC (MADVT, TENDONVI, TRANGTHAI) VALUES (SEQ17_MADVT.NEXTVAL, 'Chai', 1);
COMMIT;

-- INSERT INTO LOTHUOC
DELETE FROM LOTHUOC;

INSERT INTO LOTHUOC (MALOTHUOC, MATHUOC, NHACC, SOLUONGTON, HANSD, GIANHAP, NGAYNHAP, GIABAN) VALUES (SEQ15_MALT.NEXTVAL, 100, 'CTCP Dược Hậu Giang', 200, TO_DATE('2025-04-19', 'YYYY-MM-DD'), 5000, TO_DATE('2024-04-19', 'YYYY-MM-DD'), 10000);
INSERT INTO LOTHUOC (MALOTHUOC, MATHUOC, NHACC, SOLUONGTON, HANSD, GIANHAP, NGAYNHAP, GIABAN) VALUES (SEQ15_MALT.NEXTVAL, 101, 'FPT Retail', 150, TO_DATE('2025-04-20', 'YYYY-MM-DD'), 6000, TO_DATE('2024-04-20', 'YYYY-MM-DD'), 12000);
INSERT INTO LOTHUOC (MALOTHUOC, MATHUOC, NHACC, SOLUONGTON, HANSD, GIANHAP, NGAYNHAP, GIABAN) VALUES (SEQ15_MALT.NEXTVAL, 102, 'An Khang', 300, TO_DATE('2025-04-21', 'YYYY-MM-DD'), 7000, TO_DATE('2024-04-21', 'YYYY-MM-DD'), 15000);
COMMIT;

-- INSERT INTO DONTHUOC
DELETE FROM DONTHUOC;

INSERT INTO DONTHUOC (MADT, MAHD, MAPK, GIADT, NGAYLAP) VALUES (SEQ12_MADT.NEXTVAL, 100, 100, 25000, TO_DATE('2024-04-19', 'YYYY-MM-DD'));
INSERT INTO DONTHUOC (MADT, MAHD, MAPK, GIADT, NGAYLAP) VALUES (SEQ12_MADT.NEXTVAL, 101, 101, 30000, TO_DATE('2024-04-20', 'YYYY-MM-DD'));
INSERT INTO DONTHUOC (MADT, MAHD, MAPK, GIADT, NGAYLAP) VALUES (SEQ12_MADT.NEXTVAL, 102, 102, 35000, TO_DATE('2024-04-21', 'YYYY-MM-DD'));
COMMIT;

-- INSERT INTO CTDT
DELETE FROM CTDT;

INSERT INTO CTDT (MACTDT, MADT, MATHUOC, SOLANUONG, SOLUONGUONG, TRANGTHAIDATLICH, SOLUONGTHUOC, GHICHU) VALUES (SEQ18_MACTDT.NEXTVAL, 100, 100, 2, 1, 'Đã đặt lịch', 4, 'Ghi chú 1');
INSERT INTO CTDT (MACTDT, MADT, MATHUOC, SOLANUONG, SOLUONGUONG, TRANGTHAIDATLICH, SOLUONGTHUOC, GHICHU) VALUES (SEQ18_MACTDT.NEXTVAL, 101, 101, 3, 2, 'Đã đặt lịch', 6, 'Ghi chú 2');
INSERT INTO CTDT (MACTDT, MADT, MATHUOC, SOLANUONG, SOLUONGUONG, TRANGTHAIDATLICH, SOLUONGTHUOC, GHICHU) VALUES (SEQ18_MACTDT.NEXTVAL, 102, 102, 4, 3, 'Đã đặt lịch', 8, 'Ghi chú 3');
COMMIT;

-- INSERT INTO GIODATLICH
DELETE FROM GIODATLICH;

INSERT INTO GIODATLICH (MAGIO, MACTDT, THOIGIAN) VALUES (SEQ19_MAGIO.NEXTVAL, 1, TO_DATE('2024-04-19 08:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO GIODATLICH (MAGIO, MACTDT, THOIGIAN) VALUES (SEQ19_MAGIO.NEXTVAL, 2, TO_DATE('2024-04-20 09:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO GIODATLICH (MAGIO, MACTDT, THOIGIAN) VALUES (SEQ19_MAGIO.NEXTVAL, 3, TO_DATE('2024-04-21 10:00:00', 'YYYY-MM-DD HH24:MI:SS'));
COMMIT;

-- INSERT BANG GROUP 
DELETE FROM NHOM;

INSERT INTO NHOM (MANHOM, TENNHOM) VALUES (1, 'Admin');
INSERT INTO NHOM (MANHOM, TENNHOM) VALUES (2, 'Bác sĩ');
INSERT INTO NHOM (MANHOM, TENNHOM) VALUES (3, 'Lễ tân');
INSERT INTO NHOM (MANHOM, TENNHOM) VALUES (4, 'Bệnh nhân');
