/*========================= CAC FUNCTION TINH TOAN ========================*/

-- TINH DOANH THU THEO THANG
CREATE OR REPLACE FUNCTION TINHDOANHTHUTHEOTHANG (PAR_MONTH NUMBER, PAR_YEAR NUMBER) RETURN NUMBER
AS
  VAR_MALOAIHD LOAIHD.MALOAIHD%TYPE;
  VAR_TENLOAI LOAIHD.TENLOAIHD%TYPE;
  VAR_DOANHTHUKHAM NUMBER;
  VAR_DOANHTHUDICHVU NUMBER;
  VAR_DOANHTHUTHUOC NUMBER;
  VAR_TONGDOANHTHU NUMBER;

BEGIN

  SELECT L.MALOAIHD, L.TENLOAIHD, SUM(H.THANHTIEN)  INTO VAR_MALOAIHD, VAR_TENLOAI, VAR_DOANHTHUKHAM
  FROM HOADON H
  JOIN LOAIHD L ON L.MALOAIHD = H.MALOAIHD
  WHERE EXTRACT(YEAR FROM TDTT) = PAR_YEAR AND EXTRACT(MONTH FROM TDTT) = PAR_MONTH AND H.MALOAIHD = 1
  GROUP BY L.MALOAIHD, L.TENLOAIHD;

  SELECT L.MALOAIHD, L.TENLOAIHD, SUM(H.THANHTIEN)  INTO VAR_MALOAIHD, VAR_TENLOAI, VAR_DOANHTHUDICHVU
  FROM HOADON H
  JOIN LOAIHD L ON L.MALOAIHD = H.MALOAIHD
  WHERE EXTRACT(YEAR FROM TDTT) = PAR_YEAR AND EXTRACT(MONTH FROM TDTT) = PAR_MONTH AND H.MALOAIHD = 2
  GROUP BY L.MALOAIHD, L.TENLOAIHD;
  
  SELECT L.MALOAIHD, L.TENLOAIHD, SUM(H.THANHTIEN)  INTO VAR_MALOAIHD, VAR_TENLOAI, VAR_DOANHTHUTHUOC
  FROM HOADON H
  JOIN LOAIHD L ON L.MALOAIHD = H.MALOAIHD
  WHERE EXTRACT(YEAR FROM TDTT) = PAR_YEAR AND EXTRACT(MONTH FROM TDTT) = PAR_MONTH AND H.MALOAIHD = 3
  GROUP BY L.MALOAIHD, L.TENLOAIHD; 

  VAR_TONGDOANHTHU := VAR_DOANHTHUKHAM + VAR_DOANHTHUDICHVU + VAR_DOANHTHUTHUOC;
  RETURN VAR_TONGDOANHTHU;
  
END;
/

-- TINH SO LUONG THUOC NHAP MOI THANG
CREATE OR REPLACE FUNCTION TINHSOTHUOCNHAP (PAR_MONTH NUMBER, PAR_YEAR NUMBER) RETURN NUMBER
AS
BEGIN
  SELECT T.MATHUOC, T.TENTHUOC, SUM(SOLUONGTON)
  FROM LOTHUOC l
  JOIN THUOC t ON T.MATHUOC = L.MATHUOC
  WHERE EXTRACT(MONTH FROM L.NGAYNHAP) = 4 AND EXTRACT(YEAR FROM L.NGAYNHAP) = 2024
  GROUP BY T.MATHUOC, T.TENTHUOC;
END;
