/* ======================== INSERT DU LIEU ======================== */

-- INSERT INTO THAMSO
DELETE FORM THAMSO;

INSERT INTO THAMSO (MATHAMSO, TENTHAMSO, GIATRI) VALUES (1, 'SoLuongKhamToiDa', 30);
COMMIT;

-- INSERT INTO TAIKHOAN
DELETE FROM TAIKHOAN;
INSERT INTO TAIKHOAN (MATK, MANHOM, USERNAME, PASSWORD, TRANGTHAI) VALUES (SEQ3_MATK.NEXTVAL, 1, 'Administrator', '$2a$10$7cEO49CDMku0KntvXCX.zuvsNU8CbmYN2wkSOvaOdKqCuFpQYJyZC', 1);

INSERT INTO TAIKHOAN (MATK, MANHOM, USERNAME, PASSWORD, TRANGTHAI) VALUES (SEQ3_MATK.NEXTVAL, 4, '22520357@gm.uit.edu.vn', '$2a$10$t5pvADK/XkUxCdtvULGV4O.D.12t6tyyh6PzHEK8knLpQ3saXs2F6', 1);

-- INSERT INTO VAITRO
DELETE FROM VAITRO;

INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('100', '/benhnhan/getAll', 'Lấy danh sách bệnh nhân ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('101', '/benhnhan/insert', 'Thêm bệnh nhân ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('102', '/benhnhan/getById', 'Lấy thông tin một bệnh nhân qua ID ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('103', '/bacsi/getAll', 'Lấy danh sách bác sĩ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('104', '/account/getAllUserGroup', 'Lấy danh sách nhóm người dùng ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('105', '/account/getAllAccount', 'Lấy danh sách tài khoản ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('106', '/account/insert', 'Thêm tài khoản ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('107', '/account/updateTTCN', 'Cập nhật thông tin cá nhân ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('108', '/account/updateTTTK', 'Cập nhật thông tin tài khoản ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('109', '/account/delete', 'Xóa tài khoản ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('110', '/dichvu/getAllLDV', 'Lấy danh sách dịch vụ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('111', '/dichvu/getAll', 'Lấy danh sách dịch vụ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('112', '/dichvu/insert', 'Thêm dịch vụ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('113', '/dichvu/update', 'Cập nhật dịch vụ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('114', '/dichvu/delete', 'Xóa dịch vụ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('115', '/benh/getAll', 'Lấy danh sách bệnh ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('116', '/benh/insert', 'Thêm bệnh ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('117', '/benh/update', 'Cập nhật bệnh ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('118', '/benh/delete', 'Xóa bệnh ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('119', '/dvt/getAll', 'Lấy danh sách đơn vị thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('120', '/dvt/insert', 'Thêm đơn vị thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('121', '/dvt/update', 'Cập nhật đơn vị thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('122', '/dvt/update', 'Xóa đơn vị thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('123', '/admin/getThamSo', 'Lấy tham số ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('124', '/admin/updateThamSo', 'cập nhật tham số ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('125', '/role/getAll', 'Lấy danh sách quyền');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('126', '/role/getById', 'Lấy danh sách quyền theo ID ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('127', '/role/insert', 'Thêm quyền ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('128', '/role/update', 'Cập nhật quyền ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('129', '/role/delete', 'Xóa quyền ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('130', '/phieukham/insert-pk', 'them phieu kham ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('131', '/phieukham/insert-bn-pk', 'them benh nhan va phieu kham ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('132', '/phieukham/insert-just-pk', 'them chi phieu kham ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('133', '/phieukham/dsdk', 'lay danh sach dang ki ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('134', '/phieukham/chitiet-pk/getById', 'lay chi tiet cua mot phieu kham ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('135', '/phieukham/dspk/getById', 'lay chi tiet cua mot phieu kham');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('136', '/phieukham/ds-benh/getById', 'lay benh cua phieu kham ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('137', '/donthuoc/insert', 'them don thuoc moi ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('138', '/donthuoc/insert-ctdt', 'them ctdt don thuoc moi ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('139', '/donthuoc/ds-thuoc/getById', 'lay thuoc cua mot don thuoc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('140', '/thuoc/keDon/getAll', 'Lấy danh sách thuốc để kê đơn ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('141', '/thuoc/getAll', 'Lấy danh sách thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('142', '/thuoc/insert', 'Thêm thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('143', '/thuoc/update', 'Cập nhật thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('144', '/thuoc/delete', 'Xóa thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('145', '/lothuoc/getAll', 'Lấy danh sách lô thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('146', '/lothuoc/insert', 'Thêm lô thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('147', '/lothuoc/update', 'Cập nhật lô thuốc');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('148', '/lothuoc/delete', 'Xóa lô thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('149', '/hoadon/insert', 'Thêm hóa đơn ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('150', '/hoadon/dshd/getById', 'them hoa don ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('151', '/cls/ds-cls/getById', 'them hoa don ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('152', '/cls/getAll', 'them hoa don ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('153', '/role/assignRoleToGroup', 'Gán quyền quyền ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('154', '/lothuoc/check', 'Kiểm tra số lượng tồn các thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('155', '/account/changePassword', 'Đổi mật khẩu ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('156', '/phieukham/ttk/getById', 'Lấy thông tin khám qua mã phiếu khám ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('157', '/phieukham/update', 'Cập nhật phiếu khám ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('158', '/phieukham/ttk/dsBenh/getById', 'Lấy danh sách bệnh theo MAPK ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('159', '/benhnhan/update', 'Cập nhật thông tin bệnh nhân ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('160', '/cls/insert-just-cls', 'Thêm chỉ định cận lâm sàn ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('161', '/phieukham/update-trang-thai', 'Cập nhật trạng thái phiếu khám ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('162', '/hoadon/thanhtoan', 'thanh toán hóa đơn ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('163', '/thongke/dichvu/tt-db', 'Thống kê dịch vụ khám ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('164', '/thongke/benh', 'Thống kê bệnh ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('165', '/thongke/dichvu/cls', 'Thống kê dịch vụ cận lâm sàn ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('166', '/thongke/doanhthu-luotkhach', 'Thống kê doanh thu và lượt khách ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('167', '/thongke/chatluong', 'Thống kê chất lượng ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('168', '/phieukham/lichSuKham/getById', 'Lấy lịch sử khám của một bệnh nhân ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('169', '/cls/update-cls', 'Cập nhật thông tin cận lâm sàn');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('170', '/account/verify', 'Gửi xác thực tài khoản');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('171', '/account/confirm', 'Xác nhận tài khoản');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('172', '/account/register/tk-bn', 'Đăng kí tài khoản cho bệnh nhân chưa có hồ sơ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('173', '/account/register/tk', 'Đăng kí tài khoản cho bệnh nhân đã có hồ sơ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('174', '/usergroup/delete', 'Xóa nhóm người dùng');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('175', '/usergroup/insert', 'Thêm nhóm người dùng');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('176', '/usergroup/update', 'Cập nhật nhóm người dùng');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('177', 'ldv/insert', 'Thêm loại dịch vụ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('178', 'ldv/update', 'Cập nhật thông tin loại dịch vụ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES ('179', 'ldv/delete', 'Xóa loại dịch vụ');
COMMIT;






INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/getAll', 'Lấy danh sách quyền');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/getById', 'Lấy danh sách quyền theo ID ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/insert', 'Thêm quyền ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/update', 'Cập nhật quyền ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/delete', 'Xóa quyền ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benhnhan/getAll', 'Lấy danh sách bệnh nhân ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benhnhan/insert', 'Thêm bệnh nhân ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benhnhan/getById', 'Lấy thông tin một bệnh nhân qua ID ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/bacsi/getAll', 'Lấy danh sách bác sĩ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/getAllUserGroup', 'Lấy danh sách nhóm người dùng ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/getAllAccount', 'Lấy danh sách tài khoản ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/insert', 'Thêm tài khoản ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/updateTTCN', 'Cập nhật thông tin cá nhân ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/updateTTTK', 'Cập nhật thông tin tài khoản ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/delete', 'Xóa tài khoản ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dichvu/getAllLDV', 'Lấy danh sách dịch vụ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dichvu/getAll', 'Lấy danh sách dịch vụ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dichvu/insert', 'Thêm dịch vụ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dichvu/update', 'Cập nhật dịch vụ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dichvu/delete', 'Xóa dịch vụ ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benh/getAll', 'Lấy danh sách bệnh ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benh/insert', 'Thêm bệnh ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benh/update', 'Cập nhật bệnh ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benh/delete', 'Xóa bệnh ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dvt/getAll', 'Lấy danh sách đơn vị thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dvt/insert', 'Thêm đơn vị thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dvt/update', 'Cập nhật đơn vị thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/dvt/update', 'Xóa đơn vị thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/admin/getThamSo', 'Lấy tham số ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/admin/updateThamSo', 'Cập nhật tham số ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/insert-pk', 'Thêm phiếu khám');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/insert-bn-pk', 'Thêm bệnh nhân và phiếu khám');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/insert-just-pk', 'Thêm chỉ phiếu khám');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/dsdk', 'Hiển thị danh sách đăng ký');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/chitiet-pk/getById', 'Lấy chi tiết của một phiếu khám');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/dspk/getById', 'Lấy danh sách phiếu khám theo id');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/ds-benh/getById', 'Lấy bệnh của một phiếu kahsm');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/donthuoc/insert', 'Thêm đơn thuốc mới');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/donthuoc/insert-ctdt', 'Thêm chi tiết đơn thuốc mới');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/donthuoc/ds-thuoc/getById', 'Lấy thuốc của một đơn thuốc');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thuoc/keDon/getAll', 'Lấy danh sách thuốc để kê đơn ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thuoc/getAll', 'Lấy danh sách thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thuoc/insert', 'Thêm thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thuoc/update', 'Cập nhật thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thuoc/delete', 'Xóa thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/lothuoc/getAll', 'Lấy danh sách lô thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/lothuoc/insert', 'Thêm lô thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/lothuoc/update', 'Cập nhật lô thuốc');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/lothuoc/delete', 'Xóa lô thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/hoadon/insert', 'Thêm hóa đơn ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/hoadon/dshd/getById', 'Lấy danh sách hóa đơn theo id');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/cls/ds-cls/getById', 'Lấy danh sách cận lâm sàng theo id');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/cls/getAll', 'Lấy danh sách cận lâm sàng');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/role/assignRoleToGroup', 'Gán quyền cho nhóm người dùng');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/lothuoc/check', 'Kiểm tra số lượng tồn các thuốc ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/changePassword', 'Đổi mật khẩu ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/ttk/getById', 'Lấy thông tin khám qua mã phiếu khám ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/update', 'Cập nhật phiếu khám ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/ttk/dsBenh/getById', 'Lấy danh sách bệnh theo MAPK ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/benhnhan/update', 'Cập nhật thông tin bệnh nhân ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/cls/insert-just-cls', 'Thêm chỉ định cận lâm sàn ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/update-trang-thai', 'Cập nhật trạng thái phiếu khám ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/hoadon/thanhtoan', 'thanh toán hóa đơn ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thongke/dichvu/tt-db', 'Thống kê dịch vụ khám ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thongke/benh', 'Thống kê bệnh ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thongke/dichvu/cls', 'Thống kê dịch vụ cận lâm sàn ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thongke/doanhthu-luotkhach', 'Thống kê doanh thu và lượt khách ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/thongke/chatluong', 'Thống kê chất lượng ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/phieukham/lichSuKham/getById', 'Lấy lịch sử khám của một bệnh nhân ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/cls/update-cls', 'Cập nhật thông tin cận lâm sàn');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/verify', 'Gửi xác thực tài khoản');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/confirm', 'Xác nhận tài khoản');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/register/tk-bn', 'Đăng kí tài khoản cho bệnh nhân chưa có hồ sơ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/account/register/tk', 'Đăng kí tài khoản cho bệnh nhân đã có hồ sơ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/usergroup/delete', 'Xóa nhóm người dùng');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/usergroup/insert', 'Thêm nhóm người dùng');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, '/usergroup/update', 'Cập nhật nhóm người dùng');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, 'ldv/insert', 'Thêm loại dịch vụ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, 'ldv/update', 'Cập nhật thông tin loại dịch vụ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, 'ldv/delete', 'Xóa loại dịch vụ');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, 'datlichthuoc/getAllGioThuoc', 'Lấy tất cả giờ uống thuốc của thuốc');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, 'datlichthuoc/insert', 'Thêm giờ thuốc');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, 'datlichthuoc/update', 'Cập nhật giờ thuốc');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, 'datlichthuoc/delete', 'Xóa giờ thuốc');
INSERT INTO VAITRO (MAVAITRO, URL, MOTA) VALUES (SEQ10_MAVT.NEXTVAL, 'datlichthuoc/getAll', 'Lấy tất cả giờ uống thuốc');

INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (4, 421);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (4, 420);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (4, 422);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (4, 423);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (4, 441);
-- INSERT INTO NHOM_VAITRO
DELETE FROM NHOM_VAITRO;

INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 100);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 101);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 102);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 103);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 104);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 105);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 106);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 107);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 108);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 109);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 110);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 111);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 112);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 113);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 114);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 115);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 116);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 117);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 118);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 119);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 120);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 121);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 122);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 123);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 124);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 125);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 126);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 127);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 128);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 129);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 130);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 131);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 132);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 133);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 134);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 135);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 136);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 137);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 138);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 139);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 140);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 141);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 142);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 143);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 144);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 145);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 146);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 147);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 148);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 149);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 150);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 151);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 152);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 153);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 154);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 155);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 156);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 157);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 158);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 159);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 160);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 161);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 162);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 163);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 164);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 165);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 166);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 167);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 168);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 169);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 170);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 171);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 172);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 173);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 174);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 175);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 176);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 177);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 178);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 179);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 180);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 181);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 182);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 183);
INSERT INTO NHOM_VAITRO (MANHOM, MAVAITRO) VALUES (1, 184);
COMMIT;

-- INSERT INTO BENHNHAN
INSERT INTO BENHNHAN (MABN, MATK, CCCD, HOTEN, NGAYSINH, GIOITINH, SDT, DIACHI, TIENSUBENH, DIUNG) VALUES (SEQ2_MABN.NEXTVAL, 1, 'CCCD1', 'Nguyễn Văn A', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'Nam', '0123456789', '123 Đường ABC', 'Tiền sử bệnh 1', 'Dị ứng thuốc 1');
INSERT INTO BENHNHAN (MABN, MATK, CCCD, HOTEN, NGAYSINH, GIOITINH, SDT, DIACHI, TIENSUBENH, DIUNG) VALUES (SEQ2_MABN.NEXTVAL, 2, 'CCCD2', 'Trần Thị B', TO_DATE('1985-05-05', 'YYYY-MM-DD'), 'Nữ', '0987654321', '456 Đường XYZ', 'Tiền sử bệnh 2', 'Dị ứng thuốc 2');
INSERT INTO BENHNHAN (MABN, MATK, CCCD, HOTEN, NGAYSINH, GIOITINH, SDT, DIACHI, TIENSUBENH, DIUNG) VALUES (SEQ2_MABN.NEXTVAL, 3, 'CCCD3', 'Lê Văn C', TO_DATE('2000-10-10', 'YYYY-MM-DD'), 'Nam', '0369852147', '789 Đường LMN', 'Tiền sử bệnh 3', 'Dị ứng thuốc 3');
COMMIT;

-- INSERT INTO BACSI
DELETE FROM BACSI;

INSERT INTO BACSI (MABS, MATK, CCCD, HOTEN, TRINHDO, GIOITINH, SDT, NGAYSINH, DIACHI, CHUYENKHOA) VALUES (100, 4, 'CCCD4', 'Phạm Thị BCareFull', 'Tiến sĩ', 'Nữ', '0369852147', TO_DATE('1980-02-15', 'YYYY-MM-DD'), '789 Đường KLM', 'Chuyên khoa 1');
COMMIT;

-- INSERT INTO LETAN
DELETE FROM LETAN;
INSERT INTO LETAN (MALT, MATK, CCCD, HOTEN, SDT, NGAYSINH, DIACHI, GIOITINH) VALUES (100, 5, 'CCCD5', 'Phạm Thị a', '0369852147', TO_DATE('1980-02-15', 'YYYY-MM-DD'), '789 Đường KLM',  'Nữ');
COMMIT;

-- INSERT INTO PHONGKHAM
DELETE FROM PHONGKHAM;

INSERT INTO PHONGKHAM (MAPHONG, TENPHONG, SOPHONG, TANG) VALUES (SEQ5_MAPHONG.NEXTVAL, 'Phòng chụp X-Quang', 10, 1);
INSERT INTO PHONGKHAM (MAPHONG, TENPHONG, SOPHONG, TANG) VALUES (SEQ5_MAPHONG.NEXTVAL, 'Phòng xét nghiệm máu', 8, 2);
INSERT INTO PHONGKHAM (MAPHONG, TENPHONG, SOPHONG, TANG) VALUES (SEQ5_MAPHONG.NEXTVAL, 'Phòng khám', 12, 3);
INSERT INTO PHONGKHAM (MAPHONG, TENPHONG, SOPHONG, TANG) VALUES (SEQ5_MAPHONG.NEXTVAL, 'Phòng siêu âm', 9, 1);
COMMIT;

-- INSERT INTO BENH
DELETE FROM BENH;

INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'C16', 'U ác của dạ dày', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'M16', 'Thoái hóa khớp háng', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'A30', 'Bệnh phong [bệnh Hansen]', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'I63', 'Nhồi máu não', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'B90', 'Di chứng do lao', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'R05', 'Ho', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'R15', 'Đại tiện không kiểm soát', 1);
INSERT INTO BENH (MABENH, MAICD, TENBENH, TRANGTHAI) VALUES (SEQ6_MABENH.NEXTVAL, 'I67.2', 'Xơ vữa động mạch não', 1);
COMMIT;

-- INSERT INTO LOAIHD
DELETE FROM LOAIHD;

INSERT INTO LOAIHD (MALOAIHD, TENLOAIHD) VALUES (1, 'Hóa đơn khám');
INSERT INTO LOAIHD (MALOAIHD, TENLOAIHD) VALUES (2, 'Hóa đơn dịch vụ CLS');
INSERT INTO LOAIHD (MALOAIHD, TENLOAIHD) VALUES (3, 'Hóa đơn thuốc');
COMMIT;

-- INSERT INTO LOAIDV
DELETE FROM LOAIDV;

INSERT INTO LOAIDV (MALOAIDV, TENLOAIDV, TRANGTHAI) VALUES (SEQ9_MALDV.NEXTVAL, 'Thông thường',1);
INSERT INTO LOAIDV (MALOAIDV, TENLOAIDV, TRANGTHAI) VALUES (SEQ9_MALDV.NEXTVAL, 'Cận lâm sàn',1);
INSERT INTO LOAIDV (MALOAIDV, TENLOAIDV, TRANGTHAI) VALUES (SEQ9_MALDV.NEXTVAL, 'Đặc biệt',1);
COMMIT;


-- INSERT INTO DICHVU
DELETE FROM DICHVU;

INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 101, 'Đo điện não', 100000, 1);
INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 101, 'Chụp X-Quang', 200000, 1);
INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 100, 'Thăm khám tại phòng mạch', 300000, 1);
INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 101, 'Xét nghiệm máu', 100000, 1);
INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 102, 'Fix bug hộ', 200000, 1);
INSERT INTO DICHVU (MADV, MALOAIDV, TENDV, GIADV, TRANGTHAI) VALUES (SEQ8_MADV.NEXTVAL, 102, 'Chữa tâm thần', 300000, 1);
COMMIT;

-- INSERT INTO PHIEUKHAM
DELETE FROM PHIEUKHAM;

INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (SEQ11_MAPK.NEXTVAL, SEQ2_MABN.NEXTVAL, 100, 101, SEQ16_MAHD.NEXTVAL, SEQ5_MAPHONG.NEXTVAL, TO_DATE('2024-04-19', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 1, 120, 'Đau đầu', 170, 60, 'Đau nữa đầu', 'Bình thường', 'Không ghi chú');
INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (SEQ11_MAPK.NEXTVAL, SEQ2_MABN.NEXTVAL, 100, 102, SEQ16_MAHD.NEXTVAL, SEQ5_MAPHONG.NEXTVAL, TO_DATE('2024-04-20', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 2, 130, 'Đau bụng', 160, 50, 'Đau cu', 'Bình thường', 'Không ghi chú');
INSERT INTO PHIEUKHAM (MAPK, MABN, MABSC, MADVK, MAHD, MAPHONG, NGAYKHAM, NGAYDATLICH, TRANGTHAITH, STT, HUYETAP, LYDOKHAM, CHIEUCAO, CANNANG, TRIEUCHUNGBENH, TINHTRANGCOTHE, KETLUAN) VALUES (SEQ11_MAPK.NEXTVAL, SEQ2_MABN.NEXTVAL, 100, 103, SEQ16_MAHD.NEXTVAL, SEQ5_MAPHONG.NEXTVAL, TO_DATE('2024-04-21', 'YYYY-MM-DD'), TO_DATE('2024-04-18', 'YYYY-MM-DD'), 'Đã khám', 3, 140, 'Mệt mỏi', 180, 70, 'Đau chân', 'Bình thường', 'Không ghi chú');
COMMIT;

-- INSERT INTO KETQUADICHVUCLS
DELETE FROM KETQUADICHVUCLS;

INSERT INTO KETQUADICHVUCLS (MAKQ, MAPK, MABSTH, MADVCLS, MAPHONG, MAHD, TRANGTHAITH, STT, KETLUANCLS) VALUES (SEQ13_MAKQ.NEXTVAL, 100, 100, 101, 100, 100, 'Đã thực hiện', 1, 'Kết luận 1');
INSERT INTO KETQUADICHVUCLS (MAKQ, MAPK, MABSTH, MADVCLS, MAPHONG, MAHD, TRANGTHAITH, STT, KETLUANCLS) VALUES (SEQ13_MAKQ.NEXTVAL, 101, 100, 101, 101, 101, 'Đã thực hiện', 2, 'Kết luận 2');
INSERT INTO KETQUADICHVUCLS (MAKQ, MAPK, MABSTH, MADVCLS, MAPHONG, MAHD, TRANGTHAITH, STT, KETLUANCLS) VALUES (SEQ13_MAKQ.NEXTVAL, 102, 100, 101, 102, 102, 'Đã thực hiện', 3, 'Kết luận 3');
COMMIT;

-- INSERT INTO CHITIETBENH
DELETE FROM CHITIETBENH;

INSERT INTO CHITIETBENH (MAPK, MABENH) VALUES (100, 100);
INSERT INTO CHITIETBENH (MAPK, MABENH) VALUES (101, 102);
INSERT INTO CHITIETBENH (MAPK, MABENH) VALUES (102, 106);
COMMIT;

-- INSERT INTO HOADON
DELETE FROM HOADON;

INSERT INTO HOADON (MAHD, MALT, MALOAIHD, TDTT, TTTT, THANHTIEN, PTTT) VALUES (SEQ16_MAHD.NEXTVAL, 1, 100, TO_DATE('2024-04-19', 'YYYY-MM-DD'), 'Đã thanh toán', 150000, 'Tiền mặt');
INSERT INTO HOADON (MAHD, MALT, MALOAIHD, TDTT, TTTT, THANHTIEN, PTTT) VALUES (SEQ16_MAHD.NEXTVAL, 1, 101, TO_DATE('2024-04-20', 'YYYY-MM-DD'), 'Đã thanh toán', 200000, 'Thẻ thanh toán');
INSERT INTO HOADON (MAHD, MALT, MALOAIHD, TDTT, TTTT, THANHTIEN, PTTT) VALUES (SEQ16_MAHD.NEXTVAL, 1, 102, TO_DATE('2024-04-21', 'YYYY-MM-DD'), 'Chưa thanh toán', 300000, 'Chuyển khoản');
COMMIT;

-- INSERT INTO THUOC
DELETE FROM THUOC;

INSERT INTO THUOC (MATHUOC, MADVT, TENTHUOC, THANHPHAN, TRANGTHAI) VALUES (SEQ14_MATHUOC.NEXTVAL, 100, 'Chlorpromazin', 'Thành phần 1', 1);
INSERT INTO THUOC (MATHUOC, MADVT, TENTHUOC, THANHPHAN, TRANGTHAI) VALUES (SEQ14_MATHUOC.NEXTVAL, 101, 'Morphin', 'Thành phần 2', 1);
INSERT INTO THUOC (MATHUOC, MADVT, TENTHUOC, THANHPHAN, TRANGTHAI) VALUES (SEQ14_MATHUOC.NEXTVAL, 102, 'Insulin', 'Thành phần 3', 1);
COMMIT;

-- INSERT INTO DONVITHUOC
DELETE FROM DONVITHUOC;

INSERT INTO DONVITHUOC (MADVT, TENDONVI, TRANGTHAI) VALUES (SEQ17_MADVT.NEXTVAL, 'Viên', 1);
INSERT INTO DONVITHUOC (MADVT, TENDONVI, TRANGTHAI) VALUES (SEQ17_MADVT.NEXTVAL, 'Ống', 1);
INSERT INTO DONVITHUOC (MADVT, TENDONVI, TRANGTHAI) VALUES (SEQ17_MADVT.NEXTVAL, 'Chai', 1);
COMMIT;

-- INSERT INTO LOTHUOC
DELETE FROM LOTHUOC;

INSERT INTO LOTHUOC (MALOTHUOC, MATHUOC, NHACC, SOLUONGTON, SOLUONGNHAP, HANSD, GIANHAP, NGAYNHAP, GIABAN, TRANGTHAI) VALUES (SEQ15_MALT.NEXTVAL, 100, 'CTCP Dược Hậu Giang', 200, 200, TO_DATE('2025-04-19', 'YYYY-MM-DD'), 5000, TO_DATE('2024-04-19', 'YYYY-MM-DD'), 10000, 1);
INSERT INTO LOTHUOC (MALOTHUOC, MATHUOC, NHACC, SOLUONGTON, SOLUONGNHAP, HANSD, GIANHAP, NGAYNHAP, GIABAN, TRANGTHAI) VALUES (SEQ15_MALT.NEXTVAL, 101, 'FPT Retail', 150, 150, TO_DATE('2025-04-20', 'YYYY-MM-DD'), 6000, TO_DATE('2024-04-20', 'YYYY-MM-DD'), 12000, 1);
INSERT INTO LOTHUOC (MALOTHUOC, MATHUOC, NHACC, SOLUONGTON, SOLUONGNHAP, HANSD, GIANHAP, NGAYNHAP, GIABAN, TRANGTHAI) VALUES (SEQ15_MALT.NEXTVAL, 102, 'An Khang', 300, 300, TO_DATE('2025-04-21', 'YYYY-MM-DD'), 7000, TO_DATE('2024-04-21', 'YYYY-MM-DD'), 15000, 1);
COMMIT;

-- INSERT INTO DONTHUOC
DELETE FROM DONTHUOC;

INSERT INTO DONTHUOC (MADT, MAHD, MAPK, GIADT, NGAYLAP) VALUES (SEQ12_MADT.NEXTVAL, 100, 100, 25000, TO_DATE('2024-04-19', 'YYYY-MM-DD'));
INSERT INTO DONTHUOC (MADT, MAHD, MAPK, GIADT, NGAYLAP) VALUES (SEQ12_MADT.NEXTVAL, 101, 101, 30000, TO_DATE('2024-04-20', 'YYYY-MM-DD'));
INSERT INTO DONTHUOC (MADT, MAHD, MAPK, GIADT, NGAYLAP) VALUES (SEQ12_MADT.NEXTVAL, 102, 102, 35000, TO_DATE('2024-04-21', 'YYYY-MM-DD'));
COMMIT;

-- INSERT INTO CTDT
DELETE FROM CTDT;

INSERT INTO CTDT (MACTDT, MADT, MATHUOC, SOLANUONG, SOLUONGUONG, TRANGTHAIDATLICH, SOLUONGTHUOC, GIABANLUCKE, GHICHU) VALUES (SEQ18_MACTDT.NEXTVAL, 100, 100, 2, 1, 'Đã đặt lịch', 4, 10000, 'Ghi chú 1');
INSERT INTO CTDT (MACTDT, MADT, MATHUOC, SOLANUONG, SOLUONGUONG, TRANGTHAIDATLICH, SOLUONGTHUOC, GIABANLUCKE, GHICHU) VALUES (SEQ18_MACTDT.NEXTVAL, 101, 101, 3, 2, 'Đã đặt lịch', 6, 10000, 'Ghi chú 2');
INSERT INTO CTDT (MACTDT, MADT, MATHUOC, SOLANUONG, SOLUONGUONG, TRANGTHAIDATLICH, SOLUONGTHUOC, GIABANLUCKE, GHICHU) VALUES (SEQ18_MACTDT.NEXTVAL, 102, 102, 4, 3, 'Đã đặt lịch', 8, 10000, 'Ghi chú 3');
COMMIT;

-- INSERT INTO GIODATLICH
DELETE FROM GIODATLICH;

INSERT INTO GIODATLICH (MAGIO, MACTDT, THOIGIAN) VALUES (100, 141, '08:00');
INSERT INTO GIODATLICH (MAGIO, MACTDT, THOIGIAN) VALUES (101, 141, '10:00');
INSERT INTO GIODATLICH (MAGIO, MACTDT, THOIGIAN) VALUES (102, 145, '12:00');
COMMIT;

-- INSERT BANG GROUP 
DELETE FROM NHOM;

INSERT INTO NHOM (MANHOM, TENNHOM, TRANGTHAI) VALUES (SEQ19_MANHOM.NEXTVAL, 'Admin',1);
INSERT INTO NHOM (MANHOM, TENNHOM, TRANGTHAI) VALUES (SEQ19_MANHOM.NEXTVAL, 'Bác sĩ',1);
INSERT INTO NHOM (MANHOM, TENNHOM, TRANGTHAI) VALUES (SEQ19_MANHOM.NEXTVAL, 'Lễ tân',1);
INSERT INTO NHOM (MANHOM, TENNHOM, TRANGTHAI) VALUES (SEQ19_MANHOM.NEXTVAL, 'Bệnh nhân',1);

INSERT INTO NHOM (MANHOM, TENNHOM, TRANGTHAI) VALUES (1, 'Admin', 1);
INSERT INTO NHOM (MANHOM, TENNHOM, TRANGTHAI) VALUES (2, 'Bác sĩ',1);
INSERT INTO NHOM (MANHOM, TENNHOM, TRANGTHAI) VALUES (3, 'Lễ tân',1);
INSERT INTO NHOM (MANHOM, TENNHOM, TRANGTHAI) VALUES (4, 'Bệnh nhân',1);


SELECT * FROM NHOM;
SELECT * FROM VAITRO;
SELECT * FROM NHOM_VAITRO;
SELECT * FROM THAMSO;
SELECT * FROM TAIKHOAN;
SELECT * FROM BENHNHAN;
SELECT * FROM BACSI;
SELECT * FROM LETAN;
SELECT * FROM PHONGKHAM;
SELECT * FROM BENH;
SELECT * FROM LOAIHD;
SELECT * FROM DICHVU;
SELECT * FROM LOAIDV;
SELECT * FROM PHIEUKHAM;
SELECT * FROM KETQUADICHVUCLS;
SELECT * FROM CHITIETBENH;
SELECT * FROM DONTHUOC;
SELECT * FROM CTDT;
SELECT * FROM GIODATLICH;
SELECT * FROM THUOC;
SELECT * FROM DONVITHUOC;
SELECT * FROM LOTHUOC;
SELECT * FROM HOADON;