-- DANH SACH TRIGGER

-- 
CREATE OR REPLACE TRIGGER TRIGGER_UPDATE_TRANGTHAI_PHIEUKHAM
BEFORE UPDATE OF TTTT ON HOADON
FOR EACH ROW
DECLARE
  VAR_TTTT HOADON.TTTT%TYPE;
BEGIN

  IF :NEW.TTTT = 'Đã thanh toán' AND :NEW.MALOAIHD = 1 THEN
    BEGIN
      UPDATE PHIEUKHAM
      SET TRANGTHAITH = 'Đang thực hiện'
      WHERE (MAHD = :NEW.MAHD AND TRANGTHAITH <> 'Đã hoàn thành');
    END;
  END IF;
END;

-- Mỗi ngày khám tối đa n bệnh nhân (PHIEUKHAM)
CREATE OR REPLACE TRIGGER TRIGGER_SOLUOTKHAMTOIDA_PHIEUKHAM
BEFORE INSERT ON PHIEUKHAM
FOR EACH ROW
DECLARE
  VAR_SOBENHNHAN NUMBER;
  VAR_NGAYKHAM DATE;
  VAR_SOTOIDA NUMBER;
BEGIN
  VAR_NGAYKHAM := TRUNC(SYSDATE);

  SELECT GIATRI INTO VAR_SOTOIDA
  FROM THAMSO
  WHERE MATHAMSO = 1;

  SELECT COUNT(*) INTO VAR_SOBENHNHAN 
  FROM PHIEUKHAM
  WHERE TRUNC(NGAYKHAM) = VAR_NGAYKHAM;

  IF VAR_SOBENHNHAN >= VAR_SOTOIDA THEN
    RAISE_APPLICATION_ERROR(-20001, 'Số lượng phiếu khám đã được tạo trong ngày đã vượt quá ngưỡng tối đa.');
  END IF;
END;



-- Khi kê thuốc xong thì cập nhập lại số lượng thuốc tồn trong kho (CTDT, THUOC)
CREATE OR REPLACE TRIGGER TRG_INSERT_CTDT
AFTER INSERT ON CTDT
FOR EACH ROW
DECLARE
  VAR_SOLUONGTHUOC NUMBER;
  VAR_SOTHUOCDALAY NUMBER := 0;
BEGIN
  VAR_SOLUONGTHUOC := :NEW.SOLUONGTHUOC;

  FOR CUR_LOTHUOC IN (SELECT MALOTHUOC, SOLUONGTON 
                      FROM LOTHUOC 
                      WHERE MATHUOC = :NEW.MATHUOC AND SOLUONGTON > 0 AND HANSD > TRUNC(SYSDATE)
                      ORDER BY HANSD) 
  LOOP
    IF VAR_SOLUONGTHUOC > 0 THEN
      IF VAR_SOLUONGTHUOC >= CUR_LOTHUOC.SOLUONGTON THEN
        VAR_SOTHUOCDALAY := VAR_SOTHUOCDALAY + CUR_LOTHUOC.SOLUONGTON;
        VAR_SOLUONGTHUOC := VAR_SOLUONGTHUOC - CUR_LOTHUOC.SOLUONGTON;

        UPDATE LOTHUOC 
        SET SOLUONGTON = 0 
        WHERE MALOTHUOC = CUR_LOTHUOC.MALOTHUOC;

      ELSE
        VAR_SOTHUOCDALAY := VAR_SOTHUOCDALAY + VAR_SOLUONGTHUOC;

        UPDATE LOTHUOC 
        SET SOLUONGTON = SOLUONGTON - VAR_SOLUONGTHUOC 
        WHERE MALOTHUOC = CUR_LOTHUOC.MALOTHUOC;

        VAR_SOLUONGTHUOC := 0;
      END IF;
    ELSE
      EXIT;
    END IF;
  END LOOP;

  IF VAR_SOLUONGTHUOC > 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'So luong thuoc can ke vuot qua so luong thuoc ton trong kho');
  END IF;
  
END;
/

